/// <reference types="node" />
/**
 * Vastu Arya — Complete Products Seed (130+ products across all categories)
 * Upsert per slug — safe to run multiple times.
 */
import Product from '../models/Product';

// Premium placeholder images via placehold.co (consistent, deployment-safe)
const img = (text: string, bg = 'FFF8EE', color = 'FF6B00') =>
  `https://placehold.co/600x600/${bg}/${color}?text=${encodeURIComponent(text)}`;

export const ALL_PRODUCTS = [

  // ═══════════════════════════════════════════════════════════════
  // BRACELETS (22 products)
  // ═══════════════════════════════════════════════════════════════
  {
    name:{en:'Raw Pyrite Bracelet',hi:'कच्चा पाइराइट ब्रेसलेट'},
    slug:'raw-pyrite-bracelet', category:'bracelets',
    description:{en:'Natural raw Pyrite nugget bracelet on elastic thread. Pyrite — the Fool\'s Gold — is one of the most powerful wealth-attraction crystals. Its metallic lustre activates solar plexus chakra, amplifying willpower, ambition and financial magnetism. Wear on right wrist for career and business growth.',hi:'कच्चे पाइराइट नगेट ब्रेसलेट — सोने का पत्थर जो धन और सफलता आकर्षित करता है।'},
    benefits:['Attracts wealth & financial abundance','Activates solar plexus chakra','Boosts confidence & willpower','Shields from negative energy & envy','Enhances focus & decision making'],
    price:899, offerPrice:599,
    images:[img('Raw Pyrite Bracelet','FFF0D6','CC8800'),img('Pyrite Close Up','FFF8EE','FF6B00')],
    stock:75, sku:'VA-BR-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:1243, rating:4.8, reviewCount:312,
  },
  {
    name:{en:'Polished Pyrite Bracelet',hi:'पॉलिश पाइराइट ब्रेसलेट'},
    slug:'polished-pyrite-bracelet', category:'bracelets',
    description:{en:'High-shine polished Pyrite sphere bead bracelet. The smooth surface enhances the reflective quality of Pyrite, creating a mirror-effect that repels negativity and attracts prosperity. 8mm beads on durable elastic. Ideal for professionals, entrepreneurs and businesspeople.',hi:'चमकदार पॉलिश पाइराइट बीड ब्रेसलेट — व्यापारियों और उद्यमियों के लिए सर्वोत्तम।'},
    benefits:['Reflects & repels negative energy','Polished surface amplifies wealth energy','Solar plexus chakra activator','Boosts leadership & confidence','Business & career growth'],
    price:999, offerPrice:699,
    images:[img('Polished Pyrite Bracelet','FFF0D6','996600')],
    stock:60, sku:'VA-BR-002', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:876, rating:4.7, reviewCount:221,
  },
  {
    name:{en:'7 Chakra Bracelet',hi:'7 चक्र ब्रेसलेट'},
    slug:'7-chakra-bracelet', category:'bracelets',
    description:{en:'Seven genuine crystal beads representing each energy centre: Amethyst (Crown), Lapis Lazuli (Third Eye), Blue Sodalite (Throat), Green Aventurine (Heart), Citrine (Solar Plexus), Carnelian (Sacral), Red Jasper (Root). Balances and aligns all chakras for holistic wellbeing.',hi:'7 असली क्रिस्टल बीड — हर चक्र को संतुलित करता है।'},
    benefits:['Balances all 7 chakras','7 genuine natural crystal beads','Holistic energy alignment','Reduces anxiety & stress','Enhances spiritual awareness'],
    price:1199, offerPrice:799,
    images:[img('7 Chakra Bracelet','E8F4FD','4A90D9'),img('Chakra Stones','F0FFF0','2E8B57')],
    stock:95, sku:'VA-BR-003', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:2134, rating:4.9, reviewCount:534,
  },
  {
    name:{en:'Aquamarine Bracelet',hi:'एक्वामेरीन ब्रेसलेट'},
    slug:'aquamarine-bracelet', category:'bracelets',
    description:{en:'Natural Aquamarine bead bracelet — the Stone of Courage and Communication. Its serene ocean-blue colour calms the mind, opens the throat chakra for clear self-expression and is traditionally associated with sailors for protection during journeys. Excellent for speakers, teachers and travellers.',hi:'एक्वामेरीन ब्रेसलेट — साहस और संचार का पत्थर। यात्रियों और वक्ताओं के लिए आदर्श।'},
    benefits:['Opens throat chakra for clear communication','Calms anxiety & promotes courage','Protection during travel','Enhances self-expression','Brings clarity of thought'],
    price:1499, offerPrice:999,
    images:[img('Aquamarine Bracelet','E0F2FE','0077BE')],
    stock:45, sku:'VA-BR-004', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:423, rating:4.7, reviewCount:108,
  },
  {
    name:{en:'Black Tourmaline Bracelet',hi:'ब्लैक टूरमालाइन ब्रेसलेट'},
    slug:'black-tourmaline-bracelet', category:'bracelets',
    description:{en:'Black Tourmaline — the premier protective crystal. This bracelet forms a psychic shield around your aura, repelling negative energy, EMF radiation and ill intentions. Grounding volcanic energy stabilises emotions. Wear on left wrist to absorb incoming negative energies.',hi:'ब्लैक टूरमालाइन — सबसे शक्तिशाली सुरक्षा क्रिस्टल। नकारात्मक ऊर्जा और EMF से सुरक्षा।'},
    benefits:['Complete psychic protection','EMF and radiation shielding','Grounding & stabilising energy','Repels negativity & bad intentions','Reduces anxiety & fear'],
    price:999, offerPrice:649,
    images:[img('Black Tourmaline Bracelet','1a1a2e','AAAAAA'),img('Tourmaline Close','2C2C54','CCCCCC')],
    stock:88, sku:'VA-BR-005', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:2890, rating:4.8, reviewCount:723,
  },
  {
    name:{en:'Firoza (Turquoise) Bracelet',hi:'फिरोज़ा (टर्कोइज़) ब्रेसलेट'},
    slug:'firoza-bracelet', category:'bracelets',
    description:{en:'Natural Firoza (Turquoise) bracelet — one of the oldest known healing stones, sacred in Persian, Native American and Tibetan traditions. Blue-green Firoza is associated with Jupiter in Vedic astrology, bringing luck, prosperity and spiritual protection. Particularly beneficial for Sagittarius and Pisces.',hi:'फिरोज़ा — गुरु ग्रह का पत्थर। भाग्य, समृद्धि और आध्यात्मिक सुरक्षा के लिए।'},
    benefits:['Governs Jupiter — luck & prosperity','Protection from evil eye','Balances emotions & mood','Sacred in multiple traditions','Beneficial for Sagittarius & Pisces'],
    price:1299, offerPrice:849,
    images:[img('Firoza Bracelet','00CED1','FFFFFF')],
    stock:52, sku:'VA-BR-006', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:654, rating:4.7, reviewCount:167,
  },
  {
    name:{en:'Sulemani (Agate) Bracelet',hi:'सुलेमानी (अगेट) ब्रेसलेट'},
    slug:'sulemani-bracelet', category:'bracelets',
    description:{en:'Authentic Sulemani Hakik (Black Agate) bracelet — one of the most revered protective stones in Islamic, Hindu and folk traditions. Multi-banded black agate is believed to protect against evil eye (nazar), negative energy and jealousy. Excellent for those who deal with the public or face competition.',hi:'सुलेमानी हकीक — बुरी नजर और नकारात्मक ऊर्जा से पूर्ण सुरक्षा। प्रतिस्पर्धा में विजय।'},
    benefits:['Powerful protection from evil eye','Guards against jealousy & competition','Enhances courage & self-confidence','Calms anxiety & overthinking','Revered in multiple sacred traditions'],
    price:799, offerPrice:499,
    images:[img('Sulemani Bracelet','1C1C1C','888888')],
    stock:70, sku:'VA-BR-007', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:1123, rating:4.8, reviewCount:289,
  },
  {
    name:{en:'Clear Quartz Bracelet',hi:'क्लियर क्वार्ट्ज ब्रेसलेट'},
    slug:'clear-quartz-bracelet', category:'bracelets',
    description:{en:'Perfectly transparent Clear Quartz bead bracelet — the Master Healer. Clear Quartz amplifies intentions, energy and the properties of surrounding crystals. A powerful programmable crystal — set your intention and Clear Quartz holds and broadcasts it. Suitable for all zodiac signs.',hi:'क्लियर क्वार्ट्ज — मास्टर हीलर। सभी क्रिस्टलों की ऊर्जा को 10 गुना बढ़ाता है।'},
    benefits:['Master Healer — amplifies all energies','Programmable with your intentions','Cleanses aura & environment','Enhances clarity & focus','Compatible with all zodiac signs'],
    price:899, offerPrice:599,
    images:[img('Clear Quartz Bracelet','F0F8FF','888888')],
    stock:80, sku:'VA-BR-008', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:987, rating:4.8, reviewCount:248,
  },
  {
    name:{en:"Cat's Eye Bracelet",hi:"कैट्स आई ब्रेसलेट"},
    slug:'cats-eye-bracelet', category:'bracelets',
    description:{en:"Cat's Eye (Lehsunia) bracelet — associated with Ketu in Vedic astrology. The chatoyant shimmer of Cat's Eye is believed to protect against the evil eye, sudden losses and hidden enemies. Recommended for those going through Ketu Mahadasha or facing unexpected obstacles and setbacks.",hi:"कैट्स आई (लहसुनिया) — केतु ग्रह का पत्थर। अचानक नुकसान और छुपे दुश्मनों से सुरक्षा।"},
    benefits:["Associated with Ketu planet",'Protects against sudden losses','Guards from hidden enemies','Removes obstacles & setbacks','Evil eye protection'],
    price:1599, offerPrice:1099,
    images:[img("Cat's Eye Bracelet",'556B2F','DDDD00')],
    stock:35, sku:'VA-BR-009', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:345, rating:4.7, reviewCount:89,
  },
  {
    name:{en:'Money Magnet Bracelet',hi:'मनी मैग्नेट ब्रेसलेट'},
    slug:'money-magnet-bracelet', category:'bracelets',
    description:{en:'Powerful wealth-attraction combination bracelet featuring Citrine, Pyrite and Green Aventurine — the three most potent money crystals. This triple-power bracelet is crafted to create a constant field of financial attraction around the wearer. Ideal for entrepreneurs, traders and those seeking financial breakthrough.',hi:'सिट्रीन, पाइराइट और ग्रीन एवेंचुरीन — तीन सबसे शक्तिशाली धन क्रिस्टल का संयोजन।'},
    benefits:['Triple wealth-attraction crystal combo','Citrine — merchant stone for prosperity','Pyrite — financial shields & growth','Green Aventurine — luck magnet','Ideal for entrepreneurs & traders'],
    price:1499, offerPrice:999,
    images:[img('Money Magnet Bracelet','FFD700','1a1a00')],
    stock:65, sku:'VA-BR-010', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:1567, rating:4.9, reviewCount:392,
  },
  {
    name:{en:'Pyrite + Black Tourmaline Bracelet',hi:'पाइराइट + ब्लैक टूरमालाइन ब्रेसलेट'},
    slug:'pyrite-black-tourmaline-bracelet', category:'bracelets',
    description:{en:'The ultimate dual-purpose bracelet combining wealth attraction (Pyrite) with psychic protection (Black Tourmaline). This power combination both attracts abundance and shields the wearer from those who would block their success. Particularly effective for business owners facing competition or jealousy.',hi:'धन आकर्षण + सुरक्षा — पाइराइट और ब्लैक टूरमालाइन का शक्तिशाली संयोजन।'},
    benefits:['Wealth attraction + psychic protection','Repels those blocking your success','Business protection from competition','Dual-action wealth & shield crystal','Grounding financial energy'],
    price:1299, offerPrice:849,
    images:[img('Pyrite Tourmaline Bracelet','333300','BBBB00')],
    stock:55, sku:'VA-BR-011', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:876, rating:4.8, reviewCount:219,
  },
  {
    name:{en:'Citrine Bracelet',hi:'सिट्रीन ब्रेसलेट'},
    slug:'citrine-bracelet', category:'bracelets',
    description:{en:'Natural Citrine bead bracelet — the Merchant Stone and stone of abundance. Citrine is one of the few crystals that never needs cleansing as it transmutes negativity into positive energy. Activates solar plexus and sacral chakras, boosting creativity, motivation and financial flow. The jeweller\'s delight.',hi:'सिट्रीन — व्यापारी का पत्थर। नकारात्मकता को सकारात्मक ऊर्जा में बदलता है।'},
    benefits:['Merchant Stone — ultimate business crystal','Never needs cleansing or recharging','Activates solar plexus chakra','Boosts creativity & motivation','Attracts financial flow & success'],
    price:1199, offerPrice:799,
    images:[img('Citrine Bracelet','FFD700','664400')],
    stock:72, sku:'VA-BR-012', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:1234, rating:4.8, reviewCount:312,
  },
  {
    name:{en:'Yellow Citrine Bracelet (Premium)',hi:'येलो सिट्रीन ब्रेसलेट (प्रीमियम)'},
    slug:'yellow-citrine-bracelet-premium', category:'bracelets',
    description:{en:'Premium grade deep yellow Citrine bead bracelet with high transparency and vibrant golden hue. Natural deep-yellow Citrine is rarer and more potent than light varieties, carrying stronger solar energy for manifestation, abundance and self-confidence. Each bead is AAA quality, hand-selected.',hi:'प्रीमियम गुणवत्ता गहरे पीले सिट्रीन ब्रेसलेट — AAA क्वालिटी, हाथ से चयनित।'},
    benefits:['AAA grade premium Citrine','Deep yellow = stronger solar energy','Enhanced manifestation power','Self-confidence & optimism booster','Success in creative ventures'],
    price:1799, offerPrice:1199,
    images:[img('Yellow Citrine Premium','FFCC00','553300')],
    stock:40, sku:'VA-BR-013', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:456, rating:4.9, reviewCount:118,
  },
  {
    name:{en:'Red Jasper Bracelet',hi:'रेड जैस्पर ब्रेसलेट'},
    slug:'red-jasper-bracelet', category:'bracelets',
    description:{en:'Natural Red Jasper bracelet — the Stone of Endurance. Red Jasper\'s earthy, brick-red energy grounds and stabilises the root chakra, building stamina, determination and strength. Traditionally used by warriors, it brings courage during difficult times and helps complete long-term projects. Excellent for Aries.',hi:'रेड जैस्पर — सहनशक्ति का पत्थर। मूल चक्र को सक्रिय कर साहस और धैर्य बढ़ाता है।'},
    benefits:['Root chakra grounding & stabilisation','Builds stamina & endurance','Brings courage in difficult times','Helps complete long-term projects','Beneficial for Aries & Scorpio'],
    price:799, offerPrice:549,
    images:[img('Red Jasper Bracelet','8B0000','FFAAAA')],
    stock:68, sku:'VA-BR-014', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:789, rating:4.7, reviewCount:198,
  },
  {
    name:{en:'Lapis Lazuli Bracelet',hi:'लैपिस लाजुली ब्रेसलेट'},
    slug:'lapis-lazuli-bracelet', category:'bracelets',
    description:{en:'Royal Lapis Lazuli bracelet — one of the most sought-after stones since ancient Egypt and Mesopotamia. The deep celestial blue activates the third eye and throat chakras, enhancing wisdom, truth-seeking and communication. Sacred to royalty across civilisations, Lapis is the stone of the philosopher and king.',hi:'लैपिस लाजुली — प्राचीन मिस्र से राजाओं और दार्शनिकों का पत्थर। ज्ञान और सच्चाई का प्रतीक।'},
    benefits:['Third eye & throat chakra activation','Enhances wisdom & truth-seeking','Sacred stone of royalty & philosophers','Amplifies leadership qualities','Encourages self-expression & honesty'],
    price:1399, offerPrice:949,
    images:[img('Lapis Lazuli Bracelet','1B2A8B','GOLD')],
    stock:48, sku:'VA-BR-015', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:543, rating:4.8, reviewCount:137,
  },
  {
    name:{en:'Green Aventurine Bracelet',hi:'ग्रीन एवेंचुरीन ब्रेसलेट'},
    slug:'green-aventurine-bracelet', category:'bracelets',
    description:{en:'Natural Green Aventurine bracelet — the Stone of Opportunity and Luck. Shimmering green Aventurine is known as the luckiest of all crystals, activating the heart chakra to manifest opportunities, wealth and love. It comforter and heart healer, ideal for anyone starting new ventures or seeking a fortunate shift.',hi:'ग्रीन एवेंचुरीन — सबसे भाग्यशाली क्रिस्टल। नए अवसर और धन को आकर्षित करता है।'},
    benefits:['Luckiest crystal for opportunity','Heart chakra activation','Manifests wealth & love','Comforter and emotional healer','Ideal for new business ventures'],
    price:799, offerPrice:549,
    images:[img('Green Aventurine Bracelet','228B22','FFFFFF')],
    stock:80, sku:'VA-BR-016', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:1456, rating:4.8, reviewCount:367,
  },
  {
    name:{en:'Sodalite Bracelet',hi:'सोडालाइट ब्रेसलेट'},
    slug:'sodalite-bracelet', category:'bracelets',
    description:{en:'Sodalite bead bracelet — the Stone of Logic, Calm and Truth. Deep blue Sodalite with white calcite veins activates the third eye and throat chakras, enhancing rational thought, objectivity and self-discipline. Excellent for students, writers, researchers and anyone seeking mental clarity and focus.',hi:'सोडालाइट — तर्क, शांति और सत्य का पत्थर। छात्रों और शोधकर्ताओं के लिए उत्तम।'},
    benefits:['Enhances logic & rational thinking','Third eye & throat chakra activator','Promotes objectivity & self-discipline','Excellent for students & writers','Reduces mental fog & confusion'],
    price:899, offerPrice:599,
    images:[img('Sodalite Bracelet','1E3A8A','FFFFFF')],
    stock:60, sku:'VA-BR-017', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:432, rating:4.7, reviewCount:109,
  },
  {
    name:{en:'Sunstone Bracelet',hi:'सनस्टोन ब्रेसलेट'},
    slug:'sunstone-bracelet', category:'bracelets',
    description:{en:'Warm, sparkle-filled Sunstone bracelet — the Stone of Joy and Leadership. Sunstone\'s golden-orange shimmer carries solar energy that uplifts mood, boosts vitality and inspires leadership. Connected to the Sun and the Sacral and Solar Plexus chakras, it banishes self-doubt and illuminates personal power.',hi:'सनस्टोन — खुशी और नेतृत्व का पत्थर। आत्म-संदेह दूर कर व्यक्तिगत शक्ति को प्रकाशित करता है।'},
    benefits:['Uplifts mood & brings joy','Boosts vitality & personal power','Leadership & confidence enhancer','Banishes self-doubt & fear','Connected to the Sun energy'],
    price:1299, offerPrice:849,
    images:[img('Sunstone Bracelet','FF8C00','FFFFFF')],
    stock:45, sku:'VA-BR-018', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:312, rating:4.8, reviewCount:79,
  },
  {
    name:{en:'Moonstone Bracelet',hi:'मूनस्टोन ब्रेसलेट'},
    slug:'moonstone-bracelet', category:'bracelets',
    description:{en:'Adularescent Moonstone bracelet with the signature blue-white glow (adularescence). Moonstone is the Stone of New Beginnings, feminine energy and intuition. Associated with the Moon in Vedic astrology, it calms emotions, enhances intuition and is especially beneficial for those with a strong Moon sign or sensitive temperament.',hi:'मूनस्टोन — नई शुरुआत और अंतर्ज्ञान का पत्थर। चंद्रमा से जुड़ा — भावनाओं को शांत करता है।'},
    benefits:['Stone of New Beginnings','Enhances intuition & psychic ability','Calms emotional turbulence','Connected to Moon in Vedic astrology','Beneficial for Cancer & Pisces'],
    price:1499, offerPrice:999,
    images:[img('Moonstone Bracelet','E8E8E8','888888')],
    stock:38, sku:'VA-BR-019', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:678, rating:4.9, reviewCount:172,
  },
  {
    name:{en:'Lava + 7 Chakra Bracelet',hi:'लावा + 7 चक्र ब्रेसलेट'},
    slug:'lava-7-chakra-bracelet', category:'bracelets',
    description:{en:'Grounding Lava Stone combined with 7 Chakra crystal beads. Lava stone is a natural essential oil diffuser — add 1–2 drops of your chosen oil for aromatherapy throughout the day. The combination of volcanic Lava\'s grounding energy with all 7 chakra crystals creates a powerful full-body healing bracelet.',hi:'ज्वालामुखी लावा स्टोन + 7 चक्र क्रिस्टल — अरोमाथेरेपी डिफ्यूजर के रूप में भी उपयोग करें।'},
    benefits:['Natural essential oil diffuser','Grounding volcanic energy','All 7 chakras balanced simultaneously','Aromatherapy + crystal healing combo','Calming & stabilising'],
    price:1099, offerPrice:749,
    images:[img('Lava 7 Chakra Bracelet','2C2C2C','FF6B00')],
    stock:65, sku:'VA-BR-020', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:543, rating:4.8, reviewCount:138,
  },
  {
    name:{en:'Dhanyog Bracelet (Prosperity Combination)',hi:'धन्ययोग ब्रेसलेट'},
    slug:'dhanyog-bracelet', category:'bracelets',
    description:{en:'Dhanyog — the Yoga of Prosperity. This exclusive Vastu Arya signature bracelet combines Pyrite, Citrine, Green Aventurine and Clear Quartz in carefully calculated proportions. Based on Vastu principles of directional energy, the Dhanyog bracelet activates all four wealth quadrants simultaneously.',hi:'धन्ययोग — समृद्धि का योग। वास्तु आर्य का एक्सक्लूसिव सिग्नेचर ब्रेसलेट।'},
    benefits:['Exclusive Vastu Arya signature blend','Activates all four wealth quadrants','Pyrite + Citrine + Aventurine + Quartz','Based on Vastu directional principles','Dr. PPS Tomar curated & blessed'],
    price:1799, offerPrice:1199,
    images:[img('Dhanyog Bracelet','DAA520','FFFFFF')],
    stock:50, sku:'VA-BR-021', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:234, rating:4.9, reviewCount:62,
  },
  {
    name:{en:'Pyrite + Rose Quartz Bracelet',hi:'पाइराइट + रोज क्वार्ट्ज ब्रेसलेट'},
    slug:'pyrite-rose-quartz-bracelet', category:'bracelets',
    description:{en:'The perfect balance of wealth and love. Pyrite\'s gold-fire energy attracts money, success and recognition, while Rose Quartz\'s gentle pink energy opens the heart for love, harmony and self-worth. Together, they create a circuit of financial abundance flowing from a foundation of self-love and emotional balance.',hi:'पाइराइट + रोज क्वार्ट्ज — धन और प्रेम का संतुलन। आर्थिक सफलता और भावनात्मक सद्भाव।'},
    benefits:['Wealth attraction + heart healing','Financial confidence from self-love','Attracts love & prosperity together','Harmonises masculine & feminine energy','Boosts self-worth & relationship quality'],
    price:1299, offerPrice:849,
    images:[img('Pyrite Rose Quartz Bracelet','FF69B4','DAA520')],
    stock:58, sku:'VA-BR-022', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:678, rating:4.8, reviewCount:172,
  },

  // ═══════════════════════════════════════════════════════════════
  // CHARGING PLATES (2)
  // ═══════════════════════════════════════════════════════════════
  {
    name:{en:'Raw Selenite Charging Plate',hi:'कच्ची सेलेनाइट चार्जिंग प्लेट'},
    slug:'raw-selenite-charging-plate', category:'charging-plates',
    description:{en:'Natural raw Selenite slab charging plate. Selenite is one of the very few crystals that never needs cleansing — it continuously self-cleanses and radiates high-frequency white light energy. Place your jewellery, crystals or spiritual tools on this plate overnight to fully recharge and cleanse them. Also purifies the energy of any room.',hi:'कच्ची सेलेनाइट प्लेट — अपने क्रिस्टल, गहने और आध्यात्मिक उपकरणों को रात भर इस पर रखकर चार्ज करें।'},
    benefits:['Cleanses & recharges all crystals','Never needs its own cleansing','High-frequency white light energy','Purifies room energy instantly','Activates & amplifies other crystal energy'],
    price:1299, offerPrice:849,
    images:[img('Raw Selenite Plate','F0F0F0','CCCCCC'),img('Selenite Plate Use','FFFFF0','DDDDDD')],
    stock:35, sku:'VA-CP-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:567, rating:4.9, reviewCount:143,
  },
  {
    name:{en:'Polished Selenite Charging Plate',hi:'पॉलिश सेलेनाइट चार्जिंग प्लेट'},
    slug:'polished-selenite-charging-plate', category:'charging-plates',
    description:{en:'Smooth polished Selenite slab with a refined pearl-white surface. This elegant plate serves as a permanent altar or charging station for your crystals, jewellery and intentions. The flat polished surface allows multiple pieces to sit securely. Size: approx. 15×8cm. Includes velvet storage pouch.',hi:'पॉलिश सेलेनाइट प्लेट — क्रिस्टल और गहनों के लिए स्थायी चार्जिंग स्टेशन। 15×8cm, वेलवेट पाउच सहित।'},
    benefits:['Elegant altar & charging station','Polished surface — multiple crystals fit','Continuous energy purification','Velvet storage pouch included','Home & office energy harmoniser'],
    price:1599, offerPrice:1099,
    images:[img('Polished Selenite Plate','FFFFF0','BBBBBB')],
    stock:28, sku:'VA-CP-002', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:234, rating:4.8, reviewCount:62,
  },

  // ═══════════════════════════════════════════════════════════════
  // GEMSTONES — Natural certified gems (12)
  // ═══════════════════════════════════════════════════════════════
  {
    name:{en:'Blue Sapphire (Neelam)',hi:'नीलम (ब्लू सैफायर)'},
    slug:'blue-sapphire-neelam', category:'gemstones',
    description:{en:'Natural Ceylon/Bangkok Blue Sapphire (Neelam) — the most powerful gemstone for Saturn (Shani). Neelam acts instantly and can transform life dramatically if suitable. Always trial for 3 days before permanent wearing. Recommended after consultation with Dr. PPS Tomar to verify horoscope compatibility. Comes with GIA/IGI lab report.',hi:'नीलम — शनि का सबसे शक्तिशाली रत्न। जीवन तुरंत बदल सकता है। डॉ. पीपीएस तोमर से परामर्श के बाद ही पहनें। प्रयोगशाला रिपोर्ट सहित।'},
    benefits:['Saturn (Shani) gemstone — instant results','Career & profession growth','Removes Saturn-related obstacles','Brings discipline & focus','Authority & government support'],
    price:25000, offerPrice:18999,
    images:[img('Blue Sapphire Neelam','1B1464','4169E1')],
    stock:10, sku:'VA-GEM-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:89, rating:4.9, reviewCount:34,
  },
  {
    name:{en:'Yellow Sapphire (Pukhraj)',hi:'पुखराज (येलो सैफायर)'},
    slug:'yellow-sapphire-pukhraj', category:'gemstones',
    description:{en:'Natural Ceylon Yellow Sapphire (Pukhraj) — Jupiter\'s supreme gemstone. Jupiter governs wisdom, wealth, children, marriage and spiritual growth. Pukhraj is considered one of the safest and most beneficial gemstones with virtually no side effects. Excellent for Sagittarius, Pisces and any chart requiring Jupiter strengthening.',hi:'पुखराज — गुरु (बृहस्पति) का रत्न। ज्ञान, धन, संतान और विवाह के लिए सर्वोत्तम। लगभग कोई दुष्प्रभाव नहीं।'},
    benefits:['Jupiter gemstone — wisdom & wealth','Excellent for marriage & children','Educational & career success','Virtually side-effect free','Beneficial for Sagittarius & Pisces'],
    price:15000, offerPrice:11999,
    images:[img('Yellow Sapphire Pukhraj','FFD700','1a1a00')],
    stock:15, sku:'VA-GEM-002', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:145, rating:4.9, reviewCount:56,
  },
  {
    name:{en:'White Sapphire (Safed Pukhraj)',hi:'सफेद पुखराज (व्हाइट सैफायर)'},
    slug:'white-sapphire-safed-pukhraj', category:'gemstones',
    description:{en:'Natural White Sapphire — an affordable and effective alternative to Diamond for Venus (Shukra). Represents beauty, luxury, love, arts and marital happiness. Recommended for those whose Venus needs strengthening — brings refinement, charm and success in creative fields.',hi:'सफेद पुखराज — शुक्र (वीनस) का रत्न। हीरे का किफायती विकल्प। सौंदर्य, विवाह और कलात्मक सफलता के लिए।'},
    benefits:['Venus gemstone — love & beauty','Affordable Diamond alternative','Marital harmony & happiness','Success in arts & creative fields','Enhances charm & refinement'],
    price:8000, offerPrice:5999,
    images:[img('White Sapphire','F8F8FF','AAAAAA')],
    stock:20, sku:'VA-GEM-003', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:67, rating:4.8, reviewCount:28,
  },
  {
    name:{en:'Ruby (Manikya)',hi:'माणिक्य (रूबी)'},
    slug:'ruby-manikya', category:'gemstones',
    description:{en:'Natural Burmese/Thai Ruby (Manikya) — the Sun\'s most powerful gemstone. The fiery red of Ruby ignites the life force, boosts vitality, authority and leadership. Manikya is recommended for those with a weak Sun in their horoscope, bringing fame, government favour and professional recognition. Lab certified.',hi:'माणिक्य — सूर्य का रत्न। जीवन शक्ति, अधिकार और नेतृत्व को बढ़ाता है। सरकारी समर्थन और प्रसिद्धि दिलाता है।'},
    benefits:['Sun gemstone — vitality & authority','Boosts leadership & recognition','Government & career favour','Ignites life force & confidence','Reduces Sun-related health issues'],
    price:20000, offerPrice:14999,
    images:[img('Ruby Manikya','8B0000','FF6666')],
    stock:8, sku:'VA-GEM-004', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:56, rating:4.9, reviewCount:23,
  },
  {
    name:{en:'Red Coral (Moonga)',hi:'मूंगा (रेड कोरल)'},
    slug:'red-coral-moonga', category:'gemstones',
    description:{en:'Natural Italian/Japanese Red Coral (Moonga) — the gemstone of Mars (Mangal). Red Coral is the most recommended gemstone for those with Mangal Dosha, boosting courage, physical energy and overcoming enemies. Particularly effective for Aries and Scorpio ascendants. Helps in property matters and land disputes.',hi:'मूंगा — मंगल ग्रह का रत्न। मंगल दोष के लिए सर्वोत्तम। साहस, शारीरिक ऊर्जा और दुश्मनों पर विजय।'},
    benefits:['Mars gemstone — courage & energy','Best for Mangal Dosha','Overcomes enemies & obstacles','Property & land matters','Aries & Scorpio ascendant'],
    price:5000, offerPrice:3799,
    images:[img('Red Coral Moonga','DC143C','FFAAAA')],
    stock:25, sku:'VA-GEM-005', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:123, rating:4.8, reviewCount:45,
  },
  {
    name:{en:'Pearl (Moti)',hi:'मोती (पर्ल)'},
    slug:'pearl-moti', category:'gemstones',
    description:{en:'Natural South Sea / Freshwater Pearl (Moti) — the Moon\'s sacred gemstone. Pearl calms the mind, enhances emotional intelligence, and strengthens the Moon in the chart. Excellent for mothers, sensitive individuals, and those facing emotional turbulence, insomnia or memory issues. Worn on the little finger of right hand.',hi:'मोती — चंद्रमा का रत्न। मन को शांत करता है, भावनात्मक बुद्धि बढ़ाता है। अनिद्रा और स्मृति समस्याओं में लाभकारी।'},
    benefits:['Moon gemstone — calm & emotional balance','Enhances emotional intelligence','Helps insomnia & memory','Excellent for mothers & sensitive individuals','Reduces Moon-related mental issues'],
    price:3000, offerPrice:2299,
    images:[img('Pearl Moti','FFFFF0','CCCCCC')],
    stock:30, sku:'VA-GEM-006', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:178, rating:4.8, reviewCount:67,
  },
  {
    name:{en:'Emerald (Panna)',hi:'पन्ना (एमरल्ड)'},
    slug:'emerald-panna', category:'gemstones',
    description:{en:'Natural Colombian/Brazilian Emerald (Panna) — Mercury\'s supreme gemstone. Mercury governs intellect, communication, business, trade and technology. Panna is highly recommended for businesspeople, traders, writers and students. Brings sharp intellect, eloquence and success in commerce. Gemini and Virgo ascendants benefit most.',hi:'पन्ना — बुध ग्रह का रत्न। बुद्धि, व्यापार और तकनीक के लिए। व्यापारियों, लेखकों और छात्रों के लिए आदर्श।'},
    benefits:['Mercury gemstone — intellect & business','Sharp communication & eloquence','Business & trading success','Technology & education','Best for Gemini & Virgo ascendants'],
    price:12000, offerPrice:8999,
    images:[img('Emerald Panna','2E8B57','90EE90')],
    stock:12, sku:'VA-GEM-007', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:89, rating:4.9, reviewCount:34,
  },
  {
    name:{en:'Moissanite (Lab Diamond Alternative)',hi:'मोइसानाइट (लैब डायमंड विकल्प)'},
    slug:'moissanite-lab-diamond', category:'gemstones',
    description:{en:'Premium Moissanite — the most brilliant diamond alternative. Moissanite has a refractive index of 2.65, surpassing diamond (2.42), creating even more fire and brilliance. Ethically created, conflict-free, and a fraction of the diamond price. Provides Venus energy similar to diamond at an accessible price point.',hi:'मोइसानाइट — हीरे से भी ज्यादा चमकदार। हीरे की तुलना में बेहद किफायती। नैतिक और संघर्ष-मुक्त।'},
    benefits:['More brilliant than diamond','Ethical & conflict-free','Venus energy at fraction of diamond cost','Hardness 9.25 on Mohs scale','Certified lab-created stone'],
    price:8000, offerPrice:5999,
    images:[img('Moissanite','F0FFFF','AAAAAA')],
    stock:20, sku:'VA-GEM-008', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:45, rating:4.9, reviewCount:18,
  },
  {
    name:{en:'Hessonite (Gomed)',hi:'गोमेद (हेस्सोनाइट)'},
    slug:'hessonite-gomed', category:'gemstones',
    description:{en:'Natural Ceylon Hessonite Garnet (Gomed) — Rahu\'s gemstone. Rahu represents foreign connections, technology, mass media and unconventional paths. Gomed is highly effective during Rahu Mahadasha, bringing clarity in confusion, removing Rahu-caused delays and helping those in IT, media and foreign business sectors.',hi:'गोमेद — राहु का रत्न। राहु महादशा में अत्यंत प्रभावी। IT, मीडिया और विदेश व्यापार में सफलता।'},
    benefits:['Rahu gemstone — clarity & focus','Effective in Rahu Mahadasha','IT, media & foreign business success','Removes Rahu-caused delays','Honey-coloured Ceylon variety'],
    price:5000, offerPrice:3799,
    images:[img('Hessonite Gomed','D2691E','FFD700')],
    stock:22, sku:'VA-GEM-009', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:67, rating:4.7, reviewCount:27,
  },
  {
    name:{en:"Cat's Eye (Lehsunia)",hi:"लहसुनिया (कैट्स आई)"},
    slug:"cats-eye-lehsunia", category:'gemstones',
    description:{en:"Natural Chrysoberyl Cat's Eye (Lehsunia) — Ketu's powerful gemstone. The chatoyant shimmer moves like a cat's eye under light. Ketu represents spiritual detachment, past life karma and sudden events. Lehsunia protects against accidents, hidden enemies and sudden losses. Worn on the middle finger.",hi:"लहसुनिया — केतु का रत्न। दुर्घटनाओं, छुपे दुश्मनों और अचानक नुकसान से सुरक्षा।"},
    benefits:["Ketu gemstone — spiritual protection",'Protects against accidents & sudden loss','Reveals hidden enemies','Removes past life karma obstacles','Chatoyant — cat-eye effect'],
    price:10000, offerPrice:7499,
    images:[img("Cat's Eye Lehsunia",'556B2F','FFFF00')],
    stock:15, sku:'VA-GEM-010', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:45, rating:4.8, reviewCount:19,
  },
  {
    name:{en:'Amethyst (Natural)',hi:'एमेथिस्ट (प्राकृतिक)'},
    slug:'amethyst-natural-gemstone', category:'gemstones',
    description:{en:'Natural raw or tumbled Amethyst — the Stone of Spiritual Wisdom and Sobriety. The violet-purple colour activates the crown and third eye chakras, deepening meditation, enhancing spiritual insight and calming the overactive mind. One of the most universally loved healing crystals. Excellent for stress relief and sleep.',hi:'एमेथिस्ट — आध्यात्मिक ज्ञान का पत्थर। मुकुट और तीसरे नेत्र चक्र को सक्रिय करता है। तनाव और नींद की समस्याओं के लिए।'},
    benefits:['Crown & third eye chakra activation','Deepens meditation','Calms overactive mind','Excellent for stress & sleep','Universally safe & beneficial'],
    price:1999, offerPrice:1299,
    images:[img('Amethyst Natural','6A0DAD','DDA0DD')],
    stock:50, sku:'VA-GEM-011', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:456, rating:4.8, reviewCount:114,
  },
  {
    name:{en:'Diamond (Heera)',hi:'हीरा (डायमंड)'},
    slug:'diamond-heera', category:'gemstones',
    description:{en:'Natural certified Diamond (Heera) — Venus\'s supreme gemstone. Diamond represents luxury, beauty, love, arts and material success. High-quality diamonds with GIA/IGI certification available on request with custom pricing based on carat, cut, colour and clarity (4Cs). Please contact us for personalised diamond selection.',hi:'हीरा — शुक्र का सर्वोच्च रत्न। GIA/IGI प्रमाणित। व्यक्तिगत चयन के लिए हमसे संपर्क करें।'},
    benefits:['Supreme Venus gemstone','Luxury, love & material success','GIA/IGI certified','Custom selection by Dr. PPS Tomar','Marital harmony & artistic success'],
    price:50000, offerPrice:45000,
    images:[img('Diamond Heera','F0FFFF','AAAAAA')],
    stock:5, sku:'VA-GEM-012', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:23, rating:5.0, reviewCount:12,
  },

  // ═══════════════════════════════════════════════════════════════
  // RUDRAKSHA — 1 to 14 Mukhi + Special (16)
  // ═══════════════════════════════════════════════════════════════
  {
    name:{en:'1 Mukhi Rudraksha (Half Moon)',hi:'1 मुखी रुद्राक्ष (अर्धचंद्र)'},
    slug:'1-mukhi-rudraksha', category:'rudraksha',
    description:{en:'The rarest and most powerful Rudraksha — the 1 Mukhi. Represents Lord Shiva\'s supreme consciousness. Attains enlightenment, reduces ego and connects the wearer directly to divine consciousness. The Half-Moon form is authentic and rare. Lab tested with X-ray certification.',hi:'1 मुखी रुद्राक्ष — सबसे दुर्लभ और शक्तिशाली। भगवान शिव का प्रत्यक्ष प्रतिनिधित्व। ज्ञान और मोक्ष के लिए।'},
    benefits:['Direct connection to Lord Shiva','Highest spiritual attainment','Reduces ego & pride','Enlightenment & liberation path','Extreme rarity — X-ray certified'],
    price:15000, offerPrice:11999,
    images:[img('1 Mukhi Rudraksha','8B4513','DAA520')],
    stock:3, sku:'VA-RD-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:12, rating:5.0, reviewCount:8,
  },
  {
    name:{en:'2 Mukhi Rudraksha',hi:'2 मुखी रुद्राक्ष'},
    slug:'2-mukhi-rudraksha', category:'rudraksha',
    description:{en:'2 Mukhi Rudraksha represents the divine union of Shiva and Shakti — the masculine and feminine principles. Ideal for couples, married individuals and those seeking to balance relationships and emotional harmony. Strengthens bonds between teacher and student, parent and child.',hi:'2 मुखी रुद्राक्ष — शिव और शक्ति का मिलन। दम्पतियों और रिश्तों को मजबूत बनाने के लिए।'},
    benefits:['Shiva-Shakti union — balance & harmony','Strengthens marriage & relationships','Improves emotional balance','Teacher-student bond strengthener','Moon & mind calmer'],
    price:800, offerPrice:599,
    images:[img('2 Mukhi Rudraksha','8B4513','DAA520')],
    stock:40, sku:'VA-RD-002', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:234, rating:4.8, reviewCount:59,
  },
  {
    name:{en:'3 Mukhi Rudraksha',hi:'3 मुखी रुद्राक्ष'},
    slug:'3-mukhi-rudraksha', category:'rudraksha',
    description:{en:'3 Mukhi Rudraksha represents the Trinity — Brahma, Vishnu and Mahesh. Governed by the Fire God (Agni), it burns past karma, removes guilt and self-blame, and liberates the wearer from cycles of depression and low self-esteem. Highly recommended for those suffering from chronic fatigue or emotional baggage.',hi:'3 मुखी रुद्राक्ष — त्रिदेव का प्रतीक। पुराने कर्म, अपराधबोध और अवसाद को जलाता है।'},
    benefits:['Trinity — Brahma Vishnu Mahesh','Burns past karma & guilt','Releases depression & low self-esteem','Agni (fire) energy — purification','Chronic fatigue & lethargy cure'],
    price:600, offerPrice:449,
    images:[img('3 Mukhi Rudraksha','8B4513','DAA520')],
    stock:55, sku:'VA-RD-003', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:345, rating:4.8, reviewCount:87,
  },
  {
    name:{en:'4 Mukhi Rudraksha',hi:'4 मुखी रुद्राक्ष'},
    slug:'4-mukhi-rudraksha', category:'rudraksha',
    description:{en:'4 Mukhi Rudraksha — ruled by Brahma, the Creator. Enhances creativity, intelligence, memory and communication. Excellent for students, teachers, scientists, journalists and all those whose work requires sharp intellect and clear expression. Activates Mercury energy.',hi:'4 मुखी रुद्राक्ष — ब्रह्मा का रत्न। बुद्धि, स्मृति और संचार को बढ़ाता है। छात्रों और शिक्षकों के लिए।'},
    benefits:['Brahma energy — creativity & intelligence','Enhances memory & learning','Communication & eloquence booster','Students, teachers & journalists','Activates Mercury energy'],
    price:500, offerPrice:374,
    images:[img('4 Mukhi Rudraksha','8B4513','DAA520')],
    stock:65, sku:'VA-RD-004', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:456, rating:4.8, reviewCount:115,
  },
  {
    name:{en:'5 Mukhi Rudraksha',hi:'5 मुखी रुद्राक्ष'},
    slug:'5-mukhi-rudraksha', category:'rudraksha',
    description:{en:'The most common and universally recommended Rudraksha. 5 Mukhi represents the five forms of Shiva (Panchadev). Safe for everyone, it promotes health, peace, prosperity and spiritual growth. The standard 108+1 bead mala is most often made from 5 Mukhi beads. X-ray tested, Nepal origin.',hi:'5 मुखी रुद्राक्ष — पंचदेव का प्रतीक। सबसे सार्वभौमिक रुद्राक्ष। स्वास्थ्य, शांति और समृद्धि के लिए।'},
    benefits:['Universal — safe for everyone','Panchadev (five Shiva forms)','Health, peace & prosperity','Standard japa mala bead','Nepal origin — X-ray tested'],
    price:300, offerPrice:224,
    images:[img('5 Mukhi Rudraksha','8B4513','DAA520')],
    stock:120, sku:'VA-RD-005', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:2345, rating:4.9, reviewCount:587,
  },
  {
    name:{en:'6 Mukhi Rudraksha',hi:'6 मुखी रुद्राक्ष'},
    slug:'6-mukhi-rudraksha', category:'rudraksha',
    description:{en:'6 Mukhi Rudraksha — ruled by Lord Kartikeya (Subramanya), the general of the divine army. Builds willpower, focus, concentration and courage. Particularly beneficial for those in competitive fields — sports, exams, military, and business competition. Grounding and stabilising.',hi:'6 मुखी रुद्राक्ष — कार्तिकेय का रत्न। इच्छाशक्ति, एकाग्रता और साहस बनाता है। प्रतिस्पर्धात्मक क्षेत्रों के लिए।'},
    benefits:['Kartikeya energy — willpower & focus','Concentration & determination','Competitive advantage — sports & exams','Builds courage & confidence','Grounding & stabilising'],
    price:700, offerPrice:524,
    images:[img('6 Mukhi Rudraksha','8B4513','DAA520')],
    stock:50, sku:'VA-RD-006', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:432, rating:4.8, reviewCount:108,
  },
  {
    name:{en:'7 Mukhi Rudraksha',hi:'7 मुखी रुद्राक्ष'},
    slug:'7-mukhi-rudraksha', category:'rudraksha',
    description:{en:'7 Mukhi Rudraksha — governed by Goddess Mahalaxmi, the deity of wealth and abundance. One of the most popular Rudrakshas for financial success, this bead removes financial blockages and activates the flow of money. Highly effective for those in business, trading, or experiencing financial stagnation.',hi:'7 मुखी रुद्राक्ष — महालक्ष्मी का रत्न। वित्तीय बाधाओं को दूर कर धन का प्रवाह सक्रिय करता है।'},
    benefits:['Mahalaxmi energy — wealth & abundance','Removes financial blockages','Business & trading success','Financial stagnation cure','One of the most potent wealth Rudrakshas'],
    price:900, offerPrice:674,
    images:[img('7 Mukhi Rudraksha','8B4513','DAA520')],
    stock:45, sku:'VA-RD-007', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:876, rating:4.9, reviewCount:219,
  },
  {
    name:{en:'8 Mukhi Rudraksha',hi:'8 मुखी रुद्राक्ष'},
    slug:'8-mukhi-rudraksha', category:'rudraksha',
    description:{en:'8 Mukhi Rudraksha — ruled by Lord Ganesha, the remover of obstacles. Wearing this bead invokes Ganesha\'s blessings for success in new ventures, removal of unexpected hurdles and victory over adversity. Excellent for entrepreneurs, those beginning new projects or facing repeated failures.',hi:'8 मुखी रुद्राक्ष — गणेश का रत्न। नई शुरुआत में बाधाओं को हटाता है। उद्यमियों के लिए आदर्श।'},
    benefits:['Ganesha energy — obstacle remover','New venture blessings','Victory over adversity & failure','Entrepreneurs & new projects','Unexpected hurdle removal'],
    price:1200, offerPrice:899,
    images:[img('8 Mukhi Rudraksha','8B4513','DAA520')],
    stock:38, sku:'VA-RD-008', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:543, rating:4.8, reviewCount:137,
  },
  {
    name:{en:'9 Mukhi Rudraksha',hi:'9 मुखी रुद्राक्ष'},
    slug:'9-mukhi-rudraksha', category:'rudraksha',
    description:{en:'9 Mukhi Rudraksha — ruled by Goddess Durga (Nav Durga), representing the nine divine feminine powers. Bestows energy, fearlessness, and destroys negativity at its root. Excellent for women, those battling chronic illness and anyone seeking the blessings of the divine feminine. Connected to Ketu.',hi:'9 मुखी रुद्राक्ष — दुर्गा का रत्न। नव शक्तियां प्रदान करता है। नकारात्मकता को मूल से नष्ट करता है।'},
    benefits:['Nav Durga — nine divine powers','Destroys negativity at root','Fearlessness & courage','Excellent for women & health issues','Ketu connection — spiritual growth'],
    price:2500, offerPrice:1874,
    images:[img('9 Mukhi Rudraksha','8B4513','DAA520')],
    stock:25, sku:'VA-RD-009', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:234, rating:4.9, reviewCount:59,
  },
  {
    name:{en:'10 Mukhi Rudraksha',hi:'10 मुखी रुद्राक्ष'},
    slug:'10-mukhi-rudraksha', category:'rudraksha',
    description:{en:'10 Mukhi Rudraksha — associated with Lord Vishnu (Dashavatar — the ten incarnations). Provides protection against all ten directions. Particularly powerful for removing the malefic influence of all nine planets simultaneously. One of the most comprehensive protective Rudrakshas.',hi:'10 मुखी रुद्राक्ष — दशावतार विष्णु। दसों दिशाओं से सुरक्षा। सभी नौ ग्रहों के दुष्प्रभाव को दूर करता है।'},
    benefits:['Vishnu Dashavatar — all ten directions','Protects from all planetary malefics','Comprehensive energy shield','Overcomes obstacles from all sides','Most complete protective Rudraksha'],
    price:4000, offerPrice:2999,
    images:[img('10 Mukhi Rudraksha','8B4513','DAA520')],
    stock:20, sku:'VA-RD-010', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:178, rating:4.8, reviewCount:45,
  },
  {
    name:{en:'11 Mukhi Rudraksha',hi:'11 मुखी रुद्राक्ष'},
    slug:'11-mukhi-rudraksha', category:'rudraksha',
    description:{en:'11 Mukhi Rudraksha — ruled by the 11 Rudras (eleven aspects of Shiva). Bestows wisdom, right decision-making and protection from accidents. Excellent for those in leadership positions, those who travel frequently and anyone seeking divine protection in challenging life phases.',hi:'11 मुखी रुद्राक्ष — 11 रुद्रों का प्रतीक। सही निर्णय शक्ति और दुर्घटनाओं से सुरक्षा। नेताओं के लिए।'},
    benefits:['11 Rudras — divine wisdom','Right decision-making ability','Protection from accidents & travel','Leadership & administrative power','Challenging life phase protector'],
    price:6000, offerPrice:4499,
    images:[img('11 Mukhi Rudraksha','8B4513','DAA520')],
    stock:15, sku:'VA-RD-011', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:123, rating:4.9, reviewCount:31,
  },
  {
    name:{en:'12 Mukhi Rudraksha',hi:'12 मुखी रुद्राक्ष'},
    slug:'12-mukhi-rudraksha', category:'rudraksha',
    description:{en:'12 Mukhi Rudraksha — the Sun\'s Rudraksha, ruled by the 12 Adityas. Radiates solar energy — enhancing authority, leadership, health and vitality. Recommended for those in government, administration, senior management or anyone whose Sun needs strengthening. Removes fear and self-doubt.',hi:'12 मुखी रुद्राक्ष — सूर्य का रुद्राक्ष। अधिकार, नेतृत्व, स्वास्थ्य और जीवन शक्ति को बढ़ाता है।'},
    benefits:['Solar energy — authority & leadership','12 Adityas — divine radiance','Health, vitality & confidence','Government & senior management','Removes fear & self-doubt'],
    price:8000, offerPrice:5999,
    images:[img('12 Mukhi Rudraksha','8B4513','FF6B00')],
    stock:12, sku:'VA-RD-012', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:89, rating:4.9, reviewCount:23,
  },
  {
    name:{en:'13 Mukhi Rudraksha',hi:'13 मुखी रुद्राक्ष'},
    slug:'13-mukhi-rudraksha', category:'rudraksha',
    description:{en:'13 Mukhi Rudraksha — associated with Kamadeva, the deity of love and attraction. Rare and powerful, it fulfils all desires, attracts love and enhances charisma. Particularly beneficial for those in the beauty, fashion, entertainment and relationship counselling fields. Also strengthens Venus.',hi:'13 मुखी रुद्राक्ष — कामदेव का रत्न। सभी इच्छाओं की पूर्ति। आकर्षण और प्रेम को बढ़ाता है।'},
    benefits:['Kamadeva — love & attraction','Fulfils all worldly desires','Enhances charisma & magnetism','Beauty, fashion & entertainment','Strengthens Venus energy'],
    price:12000, offerPrice:8999,
    images:[img('13 Mukhi Rudraksha','8B4513','FF69B4')],
    stock:8, sku:'VA-RD-013', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:45, rating:4.9, reviewCount:14,
  },
  {
    name:{en:'14 Mukhi Rudraksha',hi:'14 मुखी रुद्राक्ष'},
    slug:'14-mukhi-rudraksha', category:'rudraksha',
    description:{en:'14 Mukhi Rudraksha — the Deva Mani (Jewel of the Gods), ruled by Lord Hanuman and associated with Saturn. Considered by many scholars as more powerful than the 1 Mukhi in practical spiritual benefits. Opens the Ajna (third eye) chakra, developing intuition, foresight and divine inspiration.',hi:'14 मुखी रुद्राक्ष — देव मणि। हनुमान और शनि से जुड़ा। तीसरे नेत्र चक्र को खोलता है।'},
    benefits:['Deva Mani — Jewel of Gods','Opens Ajna third eye chakra','Divine intuition & foresight','Hanuman & Saturn combined energy','Most rare among Nepali Rudrakshas'],
    price:20000, offerPrice:14999,
    images:[img('14 Mukhi Rudraksha','8B4513','DAA520')],
    stock:5, sku:'VA-RD-014', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:23, rating:5.0, reviewCount:9,
  },
  {
    name:{en:'Gaurishankar Rudraksha (Joined Pair)',hi:'गौरीशंकर रुद्राक्ष (जुड़ा जोड़ा)'},
    slug:'gaurishankar-rudraksha', category:'rudraksha',
    description:{en:'Naturally fused pair of two Rudraksha beads — representing the eternal union of Shiva (Gauri) and Parvati (Shankar). This divinely joined pair is the most sacred gift for couples and married individuals. Strengthens marriage, promotes love, harmony and mutual understanding. Deeply auspicious for home altars.',hi:'गौरीशंकर रुद्राक्ष — शिव और पार्वती के मिलन का प्रतीक। विवाहित जोड़ों के लिए सबसे पवित्र उपहार।'},
    benefits:['Natural Shiva-Parvati union bead','Most auspicious for couples','Strengthens marriage & love','Promotes harmony & understanding','Sacred altar piece for homes'],
    price:3500, offerPrice:2624,
    images:[img('Gaurishankar Rudraksha','8B4513','FF69B4')],
    stock:18, sku:'VA-RD-015', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:234, rating:4.9, reviewCount:59,
  },
  {
    name:{en:'Ganesh Rudraksha',hi:'गणेश रुद्राक्ष'},
    slug:'ganesh-rudraksha', category:'rudraksha',
    description:{en:'Rare Ganesh Rudraksha — a naturally formed Rudraksha with an elephant-trunk protrusion or trunk-like shape resembling Lord Ganesha. This extremely auspicious bead removes all obstacles, blesses new beginnings and ensures success in all undertakings. One of the most sought-after Rudraksha forms.',hi:'गणेश रुद्राक्ष — प्राकृतिक रूप से गणेश की आकृति में। सभी बाधाओं को दूर करता है। अत्यंत दुर्लभ।'},
    benefits:['Ganesha form — obstacle remover','New beginning blessings','Success in all ventures','Extremely rare natural form','Auspicious for home altar & business'],
    price:5000, offerPrice:3749,
    images:[img('Ganesh Rudraksha','8B4513','FF8C00')],
    stock:10, sku:'VA-RD-016', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:78, rating:4.9, reviewCount:24,
  },

  // ═══════════════════════════════════════════════════════════════
  // MALA (5 products)
  // ═══════════════════════════════════════════════════════════════
  {
    name:{en:'Rose Quartz Mala (108 Beads)',hi:'रोज क्वार्ट्ज माला (108 दाने)'},
    slug:'rose-quartz-mala-108', category:'sacred-mala',
    description:{en:'108+1 bead Rose Quartz crystal mala for heart-opening mantras, love visualisation and Goddess Laxmi puja. The soft pink of Rose Quartz radiates unconditional love during japa. Excellent for chanting Om Shri Maha Lakshmiyei Namah and all Venus or love-related mantras.',hi:'रोज क्वार्ट्ज माला — प्रेम और हृदय चक्र खोलने के लिए। लक्ष्मी और शुक्र के मंत्रों के लिए आदर्श।'},
    benefits:['Heart chakra opening during japa','Love & Goddess Laxmi mantras','Rose Quartz radiates unconditional love','Venus mantra enhancement','Self-love & relationship healing'],
    price:1599, offerPrice:1099,
    images:[img('Rose Quartz Mala','FFB6C1','FFFFFF')],
    stock:45, sku:'VA-ML-001', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:543, rating:4.8, reviewCount:137,
  },
  {
    name:{en:'Amethyst Mala (108 Beads)',hi:'एमेथिस्ट माला (108 दाने)'},
    slug:'amethyst-mala-108', category:'sacred-mala',
    description:{en:'Premium Amethyst crystal mala for meditation, Devi mantras and spiritual practice. The deep violet of Amethyst activates the crown chakra during japa, deepening the meditative state and accelerating spiritual progress. Excellent for Saraswati mantras, Om Namah Shivaya and all spiritual deity mantras.',hi:'एमेथिस्ट माला — ध्यान और देवी मंत्रों के लिए। मुकुट चक्र को सक्रिय कर आध्यात्मिक प्रगति को तेज करता है।'},
    benefits:['Crown chakra activation during japa','Deep meditative state enhancement','Saraswati & Shiva mantra amplification','Spiritual progress acceleration','Memory & focus during chanting'],
    price:1899, offerPrice:1299,
    images:[img('Amethyst Mala','6A0DAD','DDA0DD')],
    stock:38, sku:'VA-ML-002', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:345, rating:4.9, reviewCount:87,
  },
  {
    name:{en:'Clear Quartz Crystal Mala (108 Beads)',hi:'क्लियर क्वार्ट्ज माला (108 दाने)'},
    slug:'clear-quartz-mala-108', category:'sacred-mala',
    description:{en:'Perfectly clear Crystal Quartz 108+1 bead mala — the Master Healer mala, suitable for all deities and all mantras. Clear Quartz amplifies the intention and energy of any mantra recited. A truly universal mala that enhances the power of Gayatri, Om Namah Shivaya, Maha Mrityunjaya and all mantras equally.',hi:'क्लियर क्वार्ट्ज माला — सार्वभौमिक माला। सभी देवता और सभी मंत्रों के लिए उपयुक्त। मंत्र की शक्ति बढ़ाता है।'},
    benefits:['Universal — all deities & mantras','Amplifies any mantra recited','Master Healer energy during japa','Gayatri & Maha Mrityunjaya amplifier','Perfectly clear bead quality'],
    price:1299, offerPrice:899,
    images:[img('Clear Quartz Mala','F0F8FF','888888')],
    stock:55, sku:'VA-ML-003', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:678, rating:4.8, reviewCount:170,
  },
  {
    name:{en:'Karungali (Black Ebony Wood) Mala',hi:'करुंगली (काली एबोनी लकड़ी) माला'},
    slug:'karungali-ebony-mala', category:'sacred-mala',
    description:{en:'Sacred Karungali (Indian Black Ebony / Karungali Maram) wood mala — used in South Indian Shaiva and Shakta traditions for powerful mantra sadhana. Karungali is associated with Saturn, Kali and Shani, making it excellent for shanti puja, tantric practices and removing Shani or Rahu doshas.',hi:'करुंगली माला — शनि, काली और राहु दोषों के लिए। तांत्रिक साधना और शांति पूजा के लिए।'},
    benefits:['Saturn & Rahu dosha removal','Kali & Shiva mantra amplifier','Tantric sadhana mala','Powerful Shanti puja tool','South Indian Shaiva tradition'],
    price:999, offerPrice:699,
    images:[img('Karungali Mala','1C1C1C','888888')],
    stock:42, sku:'VA-ML-004', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:234, rating:4.8, reviewCount:59,
  },
  {
    name:{en:'Tulsi Mala (108 Sacred Beads)',hi:'तुलसी माला (108 पवित्र दाने)'},
    slug:'tulsi-mala-108-sacred', category:'sacred-mala',
    description:{en:'Sacred Tulsi (Holy Basil) mala with 108+1 genuine tulsi beads. Tulsi is the most sacred plant in Vaishnavism and is the mala of Lord Vishnu and Lord Krishna. Wearing and chanting with Tulsi mala purifies sins, removes negativity and earns Vishnu\'s grace. Fragrant and spiritually powerful.',hi:'पवित्र तुलसी माला — विष्णु और कृष्ण के भक्तों के लिए सर्वोत्तम। पाप नाशक और मोक्षदायिनी।'},
    benefits:['Most sacred for Vaishnava tradition','Lord Vishnu & Krishna mala','Purifies sins & removes negativity','Natural tulsi fragrance during japa','Grants Vishnu\'s grace & moksha'],
    price:599, offerPrice:424,
    images:[img('Tulsi Mala','1a4a1a','90EE90')],
    stock:90, sku:'VA-ML-005', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:2345, rating:4.9, reviewCount:587,
  },

  // ═══════════════════════════════════════════════════════════════
  // FRAMES (2)
  // ═══════════════════════════════════════════════════════════════
  {
    name:{en:'7 Horses Running Frame (Gold Foil)',hi:'7 दौड़ते घोड़े फ्रेम (गोल्ड फॉयल)'},
    slug:'7-horses-running-frame-gold', category:'divine-frames',
    description:{en:'Premium 7 Running Horses frame with gold foil on velvet background. The 7 Horses represent the seven rays of the Sun — speed, success, fame, prosperity and unstoppable energy. According to Vastu, placing this on the south wall of your home or office activates the fame, recognition and career zone.',hi:'7 दौड़ते घोड़े — सूर्य की 7 किरणों का प्रतीक। दक्षिण दीवार पर लगाने से करियर, प्रसिद्धि और सफलता मिलती है।'},
    benefits:['South wall career & fame zone activation','7 Sun rays — speed & success energy','Gold foil premium finish','Vastu recommended placement guide','Home & office suitable'],
    price:1499, offerPrice:999,
    images:[img('7 Horses Gold Frame','FFD700','8B0000')],
    stock:55, sku:'VA-FR-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:1234, rating:4.8, reviewCount:312,
  },
  {
    name:{en:'Vyapar Vriddhi Business Growth Frame',hi:'व्यापार वृद्धि फ्रेम'},
    slug:'vyapar-vriddhi-frame', category:'divine-frames',
    description:{en:'Exclusive Vyapar Vriddhi (Business Growth) yantra frame combining Kuber Yantra, Laxmi bija mantra, and auspicious symbols. Designed specifically for shops, offices and business establishments. Activates the North zone of wealth and draws customers, contracts and financial flow into the premises.',hi:'व्यापार वृद्धि फ्रेम — दुकान, ऑफिस के लिए। कुबेर यंत्र, लक्ष्मी बीज मंत्र और शुभ प्रतीकों का संयोजन।'},
    benefits:['Specifically designed for business premises','Kuber Yantra + Laxmi bija mantra','North zone wealth activation','Attracts customers & contracts','Dr. PPS Tomar curated & activated'],
    price:1999, offerPrice:1399,
    images:[img('Vyapar Vriddhi Frame','FFD700','228B22')],
    stock:35, sku:'VA-FR-002', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:543, rating:4.9, reviewCount:137,
  },

  // ═══════════════════════════════════════════════════════════════
  // PYRAMIDS (2)
  // ═══════════════════════════════════════════════════════════════
  {
    name:{en:'Dhan Lakshmi Pyramid',hi:'धन लक्ष्मी पिरामिड'},
    slug:'dhan-lakshmi-pyramid', category:'pyramids',
    description:{en:'Crystal Dhan Lakshmi Pyramid activated with Lakshmi bija mantras and wealth yantras. The pyramid shape focuses and amplifies energy from all four directions into a concentrated point. Place in the North of your home or office to activate the Kubera zone — the direction of all financial energy.',hi:'धन लक्ष्मी पिरामिड — लक्ष्मी मंत्र से सक्रिय। उत्तर दिशा में रखें। वित्तीय ऊर्जा का केंद्र बनाता है।'},
    benefits:['Activates Kubera (north) wealth zone','Laxmi mantra activation inside','Crystal pyramid amplifies energy','Concentrates financial energy flow','Home & office North placement'],
    price:1799, offerPrice:1199,
    images:[img('Dhan Lakshmi Pyramid','FFD700','FF6B00')],
    stock:40, sku:'VA-PY-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:456, rating:4.8, reviewCount:115,
  },
  {
    name:{en:'Citrine Pyramid (Natural Crystal)',hi:'सिट्रीन पिरामिड (प्राकृतिक क्रिस्टल)'},
    slug:'citrine-pyramid-natural', category:'pyramids',
    description:{en:'Natural Citrine crystal pyramid — the Merchant Stone in pyramid form, doubling its wealth-amplifying power. The pyramid geometry concentrates solar energy from Citrine into a powerful vortex. Never needs cleansing. Place in cash drawer, North corner or office desk for maximum financial magnetism.',hi:'प्राकृतिक सिट्रीन पिरामिड — व्यापारी पत्थर पिरामिड आकार में। नकद दराज या ऑफिस डेस्क के लिए।'},
    benefits:['Citrine pyramid — doubled wealth power','Never needs cleansing','Cash drawer financial magnetism','Solar energy concentration vortex','Office desk success amplifier'],
    price:1599, offerPrice:1099,
    images:[img('Citrine Pyramid','FFD700','664400')],
    stock:32, sku:'VA-PY-002', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:312, rating:4.8, reviewCount:79,
  },

  // ═══════════════════════════════════════════════════════════════
  // SPIRITUAL PRODUCTS (5)
  // ═══════════════════════════════════════════════════════════════
  {
    name:{en:'Money Bowl (Crystal Abundance Bowl)',hi:'मनी बाउल (क्रिस्टल समृद्धि बाउल)'},
    slug:'money-bowl-crystal-abundance', category:'spiritual',
    description:{en:'A curated crystal Money Bowl filled with wealth-attracting crystals: Pyrite nuggets, Citrine chips, Green Aventurine tumbles and Cinnamon sticks — all arranged in a singing bowl-style brass vessel. Place in the North or East of your home. A powerful Feng Shui and Vastu wealth activation tool.',hi:'मनी बाउल — पाइराइट, सिट्रीन, ग्रीन एवेंचुरीन से भरा। उत्तर या पूर्व में रखें। धन आकर्षण का शक्तिशाली उपकरण।'},
    benefits:['Multi-crystal wealth activation bowl','Pyrite + Citrine + Aventurine combo','North zone placement wealth vortex','Feng Shui & Vastu dual-system tool','Powerful home altar centre-piece'],
    price:2499, offerPrice:1699,
    images:[img('Money Bowl Crystal','FFD700','1a1a00')],
    stock:30, sku:'VA-SP-001', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:234, rating:4.9, reviewCount:62,
  },
  {
    name:{en:'7 Chakra Crystal Tree',hi:'7 चक्र क्रिस्टल ट्री'},
    slug:'7-chakra-crystal-tree', category:'spiritual',
    description:{en:'Handcrafted 7 Chakra Crystal Tree with wire-wrapped gemstone leaves representing all seven chakras on a natural Amethyst cluster base. Wire-wrapped by artisans, each tree has approximately 100–150 crystal chips. A powerful room energiser, Vastu decor piece and meditation focus object. Size: approx. 20–25cm.',hi:'7 चक्र क्रिस्टल ट्री — एमेथिस्ट बेस पर हस्तनिर्मित। 100-150 क्रिस्टल चिप्स। वास्तु सजावट और ध्यान केंद्र।'},
    benefits:['All 7 chakras represented','Natural Amethyst cluster base','100-150 genuine crystal chips','Room energy harmoniser','Meditation focus & Vastu decor'],
    price:2199, offerPrice:1499,
    images:[img('7 Chakra Crystal Tree','4B0082','FFD700')],
    stock:25, sku:'VA-SP-002', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:345, rating:4.8, reviewCount:87,
  },
  {
    name:{en:'Rose Quartz Crystal Tree',hi:'रोज क्वार्ट्ज क्रिस्टल ट्री'},
    slug:'rose-quartz-crystal-tree', category:'spiritual',
    description:{en:'Rose Quartz love and heart-healing tree with approximately 100 natural Rose Quartz chips on wire branches with a Rose Quartz crystal base. The soft pink energy fills the room with unconditional love vibrations. Place in the bedroom or relationship corner (South-West) to attract and nurture love.',hi:'रोज क्वार्ट्ज ट्री — प्रेम और हृदय उपचार। शयनकक्ष या दक्षिण-पश्चिम में रखें। प्रेम को आकर्षित और पोषित करता है।'},
    benefits:['Heart chakra room filler','100 natural Rose Quartz chips','SW corner love activation','Bedroom relationship harmoniser','Self-love energy amplifier'],
    price:1799, offerPrice:1199,
    images:[img('Rose Quartz Tree','FFB6C1','FFFFFF')],
    stock:28, sku:'VA-SP-003', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:234, rating:4.8, reviewCount:59,
  },
  {
    name:{en:'Rose Quartz Sphere',hi:'रोज क्वार्ट्ज स्फेयर'},
    slug:'rose-quartz-sphere', category:'spiritual',
    description:{en:'Polished Rose Quartz sphere — approx. 6cm diameter — with natural wooden stand. Spheres emit energy equally in all directions, creating a 360° field of loving, heart-healing energy. Perfect for the centre of a room, meditation altar or as a focal point during heart-chakra meditations.',hi:'रोज क्वार्ट्ज गोला — सभी दिशाओं में समान रूप से प्रेम ऊर्जा विकीर्ण करता है। लकड़ी का स्टैंड सहित।'},
    benefits:['360° loving energy field','All directions equal emission','Heart chakra meditation focus','Natural wooden stand included','Elegant room centre-piece'],
    price:1599, offerPrice:1099,
    images:[img('Rose Quartz Sphere','FFB6C1','FF69B4')],
    stock:22, sku:'VA-SP-004', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:178, rating:4.9, reviewCount:45,
  },
  {
    name:{en:'Amethyst Sphere',hi:'एमेथिस्ट स्फेयर'},
    slug:'amethyst-sphere', category:'spiritual',
    description:{en:'Deep purple polished Amethyst sphere — approx. 6cm diameter with wooden stand. Radiates spiritual, calming and protective energy in all directions. Placed in the meditation room, study or bedroom, the Amethyst sphere deepens sleep, reduces nightmares and creates a sanctuary of spiritual calm.',hi:'एमेथिस्ट गोला — गहरी नींद और आध्यात्मिक शांति के लिए। शयनकक्ष और ध्यान कक्ष के लिए आदर्श।'},
    benefits:['Spiritual calm 360° energy field','Deepens sleep & reduces nightmares','Study & meditation room enhancer','Protective spiritual sanctuary','Deep purple — highest vibration'],
    price:1799, offerPrice:1199,
    images:[img('Amethyst Sphere','6A0DAD','DDA0DD')],
    stock:20, sku:'VA-SP-005', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:234, rating:4.9, reviewCount:62,
  },
];

export async function seedProducts(): Promise<{ inserted: number; skipped: number }> {
  let inserted = 0, skipped = 0;
  for (const product of ALL_PRODUCTS) {
    const exists = await Product.findOne({ slug: product.slug });
    if (exists) { skipped++; } else { await Product.create(product); inserted++; }
  }
  (console as any).log(`[Seed] ${inserted} inserted, ${skipped} already existed.`);
  return { inserted, skipped };
}
