/// <reference types="node" />
/**
 * Vastu Arya — Complete Products Seed (45 products, 5 per category)
 * Uses UPSERT per slug — safe to run multiple times, never deletes existing data.
 */
import Product from '../models/Product';

const img = (text: string) =>
  `https://placehold.co/600x600/FFF8EE/FF6B00?text=${encodeURIComponent(text)}`;

export const SAMPLE_PRODUCTS = [
  // ─── DIVINE FRAMES ────────────────────────────────────────────────────────
  { name:{en:'7 Horses on Raw Pyrite Frame',hi:'पाइराइट फ्रेम पर 7 घोड़े'}, slug:'7-horses-pyrite-frame', category:'divine-frames', description:{en:'The 7 Horses symbolise the energy of the Sun, driving speed, growth, fame, and prosperity. Hang on the south or east wall. Each frame comes with a Dr. PPS Vastu placement guide.',hi:'7 घोड़े सूर्य की ऊर्जा का प्रतीक हैं। दक्षिण या पूर्व दीवार पर लगाएं।'}, benefits:['Boosts career growth & financial success','Enhances positive energy on south wall','Pyrite base attracts wealth & recognition','Dr. PPS placement guide included'], price:1499, offerPrice:999, images:[img('7 Horses Pyrite Frame'),img('7 Horses Side')], stock:48, sku:'VA-DF-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:1238, rating:4.8, reviewCount:312 },
  { name:{en:'Lord Ganesha Vastu Frame — Copper Finish',hi:'भगवान गणेश वास्तु फ्रेम'}, slug:'ganesha-vastu-copper-frame', category:'divine-frames', description:{en:'Premium copper-finish Lord Ganesha frame. Place at the main door facing inward to welcome prosperity and remove obstacles. Size: 12×14 inches.',hi:'कॉपर फिनिश गणेश फ्रेम — प्रवेश द्वार के वास्तु दोष दूर करती है।'}, benefits:['Removes Vastu doshas at main entrance','Attracts prosperity and positive visitors','Copper energises and purifies aura','Ideal housewarming & business gift'], price:1299, offerPrice:849, images:[img('Ganesha Copper Frame'),img('Ganesha Detail')], stock:35, sku:'VA-DF-002', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:876, rating:4.9, reviewCount:224 },
  { name:{en:'Laxmi–Ganesha Gold-Plated Dual Frame',hi:'लक्ष्मी–गणेश गोल्ड-प्लेटेड डुअल फ्रेम'}, slug:'laxmi-ganesha-gold-dual-frame', category:'divine-frames', description:{en:'Double-deity frame with Goddess Laxmi and Lord Ganesha in 24K gold plating — the most auspicious pairing in Vastu Shastra.',hi:'24K गोल्ड प्लेटिंग में लक्ष्मी और गणेश की दोहरी फ्रेम।'}, benefits:['Dual deity — wealth + wisdom','24K gold plating resists tarnishing','Activates North zone for financial growth','Energised with Lakshmi Ganesha mantra'], price:1999, offerPrice:1299, images:[img('Laxmi Ganesha Gold Frame')], stock:22, sku:'VA-DF-003', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:543, rating:4.8, reviewCount:136 },
  { name:{en:'Vastu Purush Yantra Frame — Blessed',hi:'वास्तु पुरुष यंत्र फ्रेम'}, slug:'vastu-purush-yantra-frame', category:'divine-frames', description:{en:'Vastu Purush yantra frame energised by Dr. PPS. Ensures all 16 directions in your home are balanced. Place in the Brahmasthana of your home.',hi:'वास्तु पुरुष फ्रेम — 16 दिशाओं में ऊर्जा संतुलित करता है।'}, benefits:['Balances all 16 Vastu directions','Removes existing Vastu doshas','Energised and activated by Dr. PPS','Best for homes undergoing renovation'], price:2499, offerPrice:1599, images:[img('Vastu Purush Yantra Frame')], stock:18, sku:'VA-DF-004', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:321, rating:4.7, reviewCount:89 },
  { name:{en:'OM Symbol 3D Wooden Vastu Frame',hi:'ओम प्रतीक 3D लकड़ी वास्तु फ्रेम'}, slug:'om-3d-wooden-vastu-frame', category:'divine-frames', description:{en:'Handcrafted 3D wooden OM frame from natural sheesham (rosewood). The OM symbol is the primordial sound of the Universe. Place at home entrance or meditation room.',hi:'शीशम लकड़ी से बनी 3D ओम फ्रेम।'}, benefits:['Hand-carved from natural sheesham wood','OM vibrations purify atmosphere','Activates spiritual energy in meditation spaces','Eco-friendly and chemical-free finish'], price:1199, offerPrice:799, images:[img('OM 3D Wooden Frame')], stock:60, sku:'VA-DF-005', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:1089, rating:4.9, reviewCount:287 },

  // ─── RUDRAKSHA ────────────────────────────────────────────────────────────
  { name:{en:'5 Mukhi Rudraksha Mala (108+1 Beads)',hi:'5 मुखी रुद्राक्ष माला'}, slug:'5-mukhi-rudraksha-mala-108', category:'rudraksha', description:{en:'Sourced from Nepal, these 5 Mukhi Rudraksha beads represent Lord Shiva. 108+1 bead mala energised for daily japa, meditation, and spiritual protection. X-ray tested for authenticity.',hi:'नेपाल से प्राप्त 5 मुखी रुद्राक्ष माला — भगवान शिव का प्रतीक।'}, benefits:['Calms mind & reduces stress','Boosts concentration & spiritual growth','Protects against negative energies','Certificate of authenticity included'], price:1799, offerPrice:1199, images:[img('5 Mukhi Rudraksha Mala')], stock:65, sku:'VA-RU-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:2140, rating:4.9, reviewCount:542 },
  { name:{en:'1 Mukhi Half Moon Rudraksha — Rare',hi:'1 मुखी अर्धचंद्र रुद्राक्ष — दुर्लभ'}, slug:'1-mukhi-half-moon-rudraksha', category:'rudraksha', description:{en:'The rarest Rudraksha — the 1 Mukhi Half Moon. Ruled by the Sun, bestows enlightenment, clarity, and supreme consciousness. Lab-tested with certificate.',hi:'1 मुखी अर्धचंद्र रुद्राक्ष — सबसे दुर्लभ।'}, benefits:['Governs the Sun — health & leadership','Boosts clarity and decision-making','Lab-tested & certified authentic','Enhances spiritual consciousness'], price:4999, offerPrice:2999, images:[img('1 Mukhi Rudraksha')], stock:8, sku:'VA-RU-002', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:198, rating:4.9, reviewCount:67 },
  { name:{en:'7 Mukhi Rudraksha Pendant — Silver Capped',hi:'7 मुखी रुद्राक्ष पेंडेंट'}, slug:'7-mukhi-rudraksha-silver-pendant', category:'rudraksha', description:{en:'7 Mukhi Rudraksha in pure silver cap with black thread. Governed by Goddess Mahalaxmi, attracts wealth and removes financial blockages.',hi:'7 मुखी रुद्राक्ष शुद्ध चांदी कैप में — महालक्ष्मी द्वारा शासित।'}, benefits:['Governed by Goddess Mahalaxmi','Removes financial blockages','Pure silver cap — no nickel','Energised by IVAF expert Dr. PPS'], price:999, offerPrice:649, images:[img('7 Mukhi Pendant')], stock:42, sku:'VA-RU-003', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:789, rating:4.8, reviewCount:198 },
  { name:{en:'Gauri Shankar Rudraksha — Love & Unity',hi:'गौरी शंकर रुद्राक्ष'}, slug:'gauri-shankar-rudraksha-pair', category:'rudraksha', description:{en:'Naturally joined pair symbolising the union of Shiva and Parvati. Strengthens marital bonds, promotes love, and harmonises relationships.',hi:'गौरी शंकर रुद्राक्ष — शिव और पार्वती के मिलन का प्रतीक।'}, benefits:['Strengthens marital bonds','Promotes love & understanding','Best gifted to couples','Natural joined pair — not glued'], price:2499, offerPrice:1699, images:[img('Gauri Shankar Rudraksha')], stock:15, sku:'VA-RU-004', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:432, rating:4.9, reviewCount:112 },
  { name:{en:'Rudraksha Bracelet — 5 Mukhi (10mm)',hi:'रुद्राक्ष ब्रेसलेट — 5 मुखी'}, slug:'rudraksha-bracelet-5-mukhi-10mm', category:'rudraksha', description:{en:'5 Mukhi Rudraksha bracelet with 10mm beads on elastic thread. Energised with Shiva mantras. Brings peace, focus, and protection. Fits all wrists.',hi:'10mm के 5 मुखी रुद्राक्ष ब्रेसलेट — शांति और सुरक्षा के लिए।'}, benefits:['Easy to wear daily','Shiva mantra energised','Elastic thread — fits all wrists','Promotes calm and focus'], price:799, offerPrice:499, images:[img('Rudraksha Bracelet')], stock:88, sku:'VA-RU-005', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:1654, rating:4.7, reviewCount:421 },

  // ─── GEMSTONES ────────────────────────────────────────────────────────────
  { name:{en:'Natural Amethyst Cluster — Positive Vibes',hi:'प्राकृतिक एमेथिस्ट क्लस्टर'}, slug:'amethyst-cluster-positive-energy', category:'gemstones', description:{en:'Raw natural Amethyst cluster (150-200g). Stone of spiritual wisdom and inner peace. Place in bedroom or meditation space to cleanse the aura.',hi:'प्राकृतिक एमेथिस्ट क्लस्टर — आध्यात्मिक ज्ञान का पत्थर।'}, benefits:['Purifies negative energy','Promotes restful sleep','Enhances intuition','Each piece unique — natural variation'], price:1299, offerPrice:849, images:[img('Amethyst Cluster')], stock:31, sku:'VA-GS-001', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:389, rating:4.7, reviewCount:95 },
  { name:{en:'Rose Quartz Heart — Love & Harmony Stone',hi:'रोज क्वार्ट्ज हार्ट'}, slug:'rose-quartz-heart-love-stone', category:'gemstones', description:{en:'Hand-polished Rose Quartz heart (60-80g). Opens the heart chakra, promotes love, compassion, and emotional healing.',hi:'हाथ से पॉलिश रोज क्वार्ट्ज हार्ट — प्रेम का पत्थर।'}, benefits:['Opens heart chakra','Promotes love & compassion','Emotional healing stone','Place in SW corner for relationships'], price:899, offerPrice:599, images:[img('Rose Quartz Heart')], stock:55, sku:'VA-GS-002', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:723, rating:4.8, reviewCount:187 },
  { name:{en:'Black Tourmaline Raw Crystal — EMF Protection',hi:'ब्लैक टूरमालाइन — EMF सुरक्षा'}, slug:'black-tourmaline-emf-protection', category:'gemstones', description:{en:'Raw Black Tourmaline crystal (100-150g) for EMF protection and grounding. Place near WiFi router, TV, or computer to neutralise radiation.',hi:'ब्लैक टूरमालाइन — EMF विकिरण से सुरक्षा।'}, benefits:['Blocks harmful EMF radiation','Provides psychic protection','Grounding & stabilising energy','Best near electronics & WiFi routers'], price:1099, offerPrice:699, images:[img('Black Tourmaline')], stock:44, sku:'VA-GS-003', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:512, rating:4.6, reviewCount:134 },
  { name:{en:'Citrine Pyramid — Wealth Manifestation',hi:'सिट्रीन पिरामिड — धन आकर्षण'}, slug:'citrine-pyramid-wealth', category:'gemstones', description:{en:'Natural Citrine pyramid (approx. 100g). The merchant stone — attracts money, success, and abundance. Place in North or Northwest of home or business.',hi:'प्राकृतिक सिट्रीन पिरामिड — व्यापार और धन के लिए।'}, benefits:['Attracts money & business success','Place in North for career growth','Self-cleansing stone — no maintenance','No negative energy absorption'], price:1599, offerPrice:999, images:[img('Citrine Pyramid')], stock:27, sku:'VA-GS-004', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:634, rating:4.8, reviewCount:162 },
  { name:{en:'Clear Quartz Crystal Ball (60mm) — Master Healer',hi:'क्लियर क्वार्ट्ज क्रिस्टल बॉल (60mm)'}, slug:'clear-quartz-crystal-ball-60mm', category:'gemstones', description:{en:'Perfectly spherical 60mm Clear Quartz ball — the Master Healer. Amplifies energy of all other stones. Comes with wooden stand and velvet pouch.',hi:'60mm क्लियर क्वार्ट्ज क्रिस्टल बॉल — सभी क्रिस्टल का मास्टर हीलर।'}, benefits:['Amplifies energy of all stones','Raises vibration of entire room','Wooden stand & velvet pouch included','Excellent for meditation and healing'], price:2199, offerPrice:1399, images:[img('Crystal Ball 60mm')], stock:19, sku:'VA-GS-005', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:445, rating:4.9, reviewCount:118 },

  // ─── YANTRAS ─────────────────────────────────────────────────────────────
  { name:{en:'Shree Yantra in Rose Quartz Crystal',hi:'रोज क्वार्ट्ज श्री यंत्र'}, slug:'shree-yantra-rose-quartz', category:'yantras', description:{en:'Hand-carved from pure Rose Quartz, energised with Lakshmi mantras. Activates abundance, love, and prosperity. Place facing East.',hi:'शुद्ध रोज क्वार्ट्ज श्री यंत्र — लक्ष्मी मंत्र से ऊर्जावान।'}, benefits:['Attracts wealth & abundance','Activates divine feminine energy','Clears negative energy','Energised by IVAF Certified expert'], price:2199, offerPrice:1499, images:[img('Shree Yantra Rose Quartz')], stock:22, sku:'VA-YA-001', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:847, rating:4.9, reviewCount:198 },
  { name:{en:'Sphatik Shivalinga with Vastu Guide',hi:'स्फटिक शिवलिंग वास्तु गाइड सहित'}, slug:'sphatik-shivalinga-vastu', category:'yantras', description:{en:'Pure Sphatik Shivalinga (50-60g) energised with Maha Mrityunjaya mantras. Comes with detailed Vastu placement guide by Dr. PPS.',hi:'स्फटिक शिवलिंग — महामृत्युंजय मंत्र से ऊर्जावान।'}, benefits:['Removes Vastu doshas','Health, peace & divine blessings','Amplifies pooja space energy','Premium gift packaging available'], price:999, offerPrice:699, images:[img('Sphatik Shivalinga')], stock:54, sku:'VA-YA-002', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:1087, rating:4.8, reviewCount:278 },
  { name:{en:'Kuber Yantra — North Wall Wealth Activator',hi:'कुबेर यंत्र — उत्तर दीवार धन सक्रियक'}, slug:'kuber-yantra-wealth', category:'yantras', description:{en:'Most powerful tool for financial abundance. Made on copper sheet, energised with Kuber mantras by Dr. PPS. Place on North wall.',hi:'कुबेर यंत्र — सबसे शक्तिशाली धन यंत्र।'}, benefits:['Activates North zone wealth energy','Removes financial obstacles','Copper base — maximum conductivity','Mantra energised by Dr. PPS'], price:1799, offerPrice:1199, images:[img('Kuber Yantra')], stock:38, sku:'VA-YA-003', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:678, rating:4.7, reviewCount:176 },
  { name:{en:'Vastu Dosh Nivaran Yantra — Full Home',hi:'वास्तु दोष निवारण यंत्र'}, slug:'vastu-dosh-nivaran-yantra', category:'yantras', description:{en:'Corrects all major Vastu defects in one go. Made on gold-plated copper, energised for 3 months by Dr. PPS.',hi:'वास्तु दोष निवारण यंत्र — सभी प्रमुख वास्तु दोष ठीक करता है।'}, benefits:['Corrects all major Vastu defects','No renovation needed','Gold-plated copper — long lasting','Energised for 3 months by Dr. PPS'], price:2999, offerPrice:1999, images:[img('Vastu Dosh Yantra')], stock:14, sku:'VA-YA-004', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:312, rating:4.8, reviewCount:89 },
  { name:{en:'Navgrah Yantra — Nine Planet Balancer',hi:'नवग्रह यंत्र — नौ ग्रह संतुलनकर्ता'}, slug:'navgrah-yantra-nine-planets', category:'yantras', description:{en:'Pacifies all nine planets and removes their malefic effects. Made on pure copper, energised with all nine planetary mantras.',hi:'नवग्रह यंत्र — सभी नौ ग्रहों को शांत करता है।'}, benefits:['Pacifies all nine planets','Removes malefic planetary effects','Pure copper sheet — authentic','Best with Dr. PPS consultation'], price:2499, offerPrice:1699, images:[img('Navgrah Yantra')], stock:25, sku:'VA-YA-005', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:234, rating:4.6, reviewCount:67 },

  // ─── GEMSTONE PENDANTS ────────────────────────────────────────────────────
  { name:{en:'Natural Citrine Gemstone Pendant — Gold Wire',hi:'प्राकृतिक सिट्रीन पेंडेंट'}, slug:'citrine-gemstone-pendant-gold', category:'gemstone-pendants', description:{en:'Natural Citrine faceted pendant in gold-plated wire wrap. Success and abundance stone. Wear to attract financial growth and boost confidence.',hi:'प्राकृतिक सिट्रीन पेंडेंट — सफलता और समृद्धि के लिए।'}, benefits:['Attracts financial success','Boosts confidence & self-esteem','Gold-plated wire — hypoallergenic','Certificate of natural gemstone'], price:3500, offerPrice:1750, images:[img('Citrine Gold Pendant')], stock:25, sku:'VA-GP-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:567, rating:4.8, reviewCount:143 },
  { name:{en:'Amethyst Teardrop Pendant — Calming Energy',hi:'एमेथिस्ट टियरड्रॉप पेंडेंट'}, slug:'amethyst-teardrop-pendant', category:'gemstone-pendants', description:{en:'Genuine Amethyst teardrop pendant in sterling silver setting. Calms the mind, improves sleep, and enhances intuition.',hi:'असली एमेथिस्ट पेंडेंट स्टर्लिंग सिल्वर में — मन को शांत करता है।'}, benefits:['Calms anxiety & overthinking','Improves sleep quality','Sterling silver — certified','Best for students & meditators'], price:1999, offerPrice:1299, images:[img('Amethyst Teardrop Pendant')], stock:33, sku:'VA-GP-002', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:389, rating:4.7, reviewCount:98 },
  { name:{en:'Rose Quartz Oval Pendant — Love Magnet',hi:'रोज क्वार्ट्ज ओवल पेंडेंट'}, slug:'rose-quartz-oval-pendant', category:'gemstone-pendants', description:{en:'Polished Rose Quartz oval pendant in rose-gold plated brass. Opens heart chakra, attracts love, and heals emotional wounds.',hi:'रोज क्वार्ट्ज पेंडेंट — हृदय चक्र खोलता है।'}, benefits:['Opens heart chakra','Attracts love & relationships','Rose-gold plating — tarnish-resistant','Emotional healing & self-love'], price:1499, offerPrice:899, images:[img('Rose Quartz Pendant')], stock:48, sku:'VA-GP-003', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:712, rating:4.8, reviewCount:187 },
  { name:{en:'Labradorite Cabochon Pendant — Intuition Stone',hi:'लैब्राडोराइट पेंडेंट'}, slug:'labradorite-cabochon-pendant', category:'gemstone-pendants', description:{en:'Stunning Labradorite cabochon pendant with magical blue-green flash. Enhances psychic abilities, protects the aura, and stimulates creativity.',hi:'लैब्राडोराइट पेंडेंट — मानसिक क्षमताएं बढ़ाता है।'}, benefits:['Enhances intuition & psychic ability','Protects aura from energy drains','Stimulates creativity','Unique labradorescence in every piece'], price:2299, offerPrice:1499, images:[img('Labradorite Pendant')], stock:20, sku:'VA-GP-004', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:245, rating:4.9, reviewCount:72 },
  { name:{en:'Green Aventurine Pendant — Luck & Prosperity',hi:'ग्रीन एवेंचुरीन पेंडेंट'}, slug:'green-aventurine-pendant-luck', category:'gemstone-pendants', description:{en:'Natural Green Aventurine pendant in gold-filled wire. Stone of opportunity — manifests prosperity and luck. Wear during interviews or exams.',hi:'ग्रीन एवेंचुरीन पेंडेंट — अवसर और सौभाग्य का पत्थर।'}, benefits:['Manifests luck & opportunity','Boosts confidence in challenges','Gold-filled wire — durable','Best for students & job seekers'], price:1299, offerPrice:799, images:[img('Green Aventurine Pendant')], stock:56, sku:'VA-GP-005', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:934, rating:4.7, reviewCount:234 },

  // ─── BOX BRACELET ─────────────────────────────────────────────────────────
  { name:{en:'7 Chakra Box Bracelet — Energy Balance',hi:'7 चक्र बॉक्स ब्रेसलेट'}, slug:'7-chakra-box-bracelet', category:'box-bracelet', description:{en:'7 Chakra Box Bracelet featuring 7 genuine gemstone beads representing each chakra. Balances all energy centres from Root to Crown.',hi:'7 चक्र बॉक्स ब्रेसलेट — सभी 7 ऊर्जा केंद्रों को संतुलित करता है।'}, benefits:['Balances all 7 chakras','7 genuine gemstone beads','Premium gift box included','Suitable for men and women'], price:1499, offerPrice:899, images:[img('7 Chakra Box Bracelet')], stock:72, sku:'VA-BB-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:1876, rating:4.8, reviewCount:478 },
  { name:{en:'Tiger Eye Box Bracelet — Confidence & Power',hi:'टाइगर आई बॉक्स ब्रेसलेट'}, slug:'tiger-eye-box-bracelet', category:'box-bracelet', description:{en:'Premium Tiger Eye bead bracelet in luxury gift box. Stone of courage, confidence, and clarity. Wear to overcome fear and achieve goals.',hi:'टाइगर आई ब्रेसलेट — साहस और आत्मविश्वास का पत्थर।'}, benefits:['Boosts confidence & courage','Sharpens decision-making','Protects from negative energy','Luxury gift box included'], price:1199, offerPrice:749, images:[img('Tiger Eye Box Bracelet')], stock:64, sku:'VA-BB-002', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:1123, rating:4.7, reviewCount:289 },
  { name:{en:'Black Obsidian Protection Box Bracelet',hi:'ब्लैक ओब्सीडियन प्रोटेक्शन ब्रेसलेट'}, slug:'black-obsidian-protection-bracelet', category:'box-bracelet', description:{en:'Black Obsidian bracelet in premium gift box. Ultimate protection stone — creates shield against negativity, psychic attacks, and bad intentions.',hi:'ब्लैक ओब्सीडियन ब्रेसलेट — नकारात्मकता और बुरी नजर से पूर्ण सुरक्षा।'}, benefits:['Complete protection from negativity','Shields against psychic attacks','Grounding volcanic glass stone','Premium gift box & auth. card'], price:999, offerPrice:649, images:[img('Black Obsidian Bracelet')], stock:83, sku:'VA-BB-003', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:2134, rating:4.8, reviewCount:547 },
  { name:{en:'Amethyst Healing Box Bracelet — Calm Mind',hi:'एमेथिस्ट हीलिंग ब्रेसलेट'}, slug:'amethyst-healing-box-bracelet', category:'box-bracelet', description:{en:'Amethyst bead bracelet in luxury gift box with healing card. Soothes anxiety, stops overthinking, and brings mental clarity.',hi:'एमेथिस्ट ब्रेसलेट — मन को शांत करता है।'}, benefits:['Soothes anxiety & overthinking','Mental clarity & focus','Healing card included','Best for students & professionals'], price:1099, offerPrice:699, images:[img('Amethyst Healing Bracelet')], stock:59, sku:'VA-BB-004', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:876, rating:4.7, reviewCount:223 },
  { name:{en:'Rose Quartz Love Box Bracelet — Gift Set',hi:'रोज क्वार्ट्ज लव ब्रेसलेट गिफ्ट सेट'}, slug:'rose-quartz-love-bracelet-gift', category:'box-bracelet', description:{en:'Rose Quartz bead bracelet gift set including bracelet, matching pendant, and a love crystal card. Perfect for Valentine or anniversary.',hi:'रोज क्वार्ट्ज लव गिफ्ट सेट — ब्रेसलेट, पेंडेंट, और लव क्रिस्टल कार्ड।'}, benefits:['Complete love crystal set','Opens heart chakra','Bracelet + pendant combo','Perfect for Valentine & anniversaries'], price:1999, offerPrice:1199, images:[img('Rose Quartz Gift Set')], stock:41, sku:'VA-BB-005', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:1098, rating:4.9, reviewCount:312 },

  // ─── SACRED MALA ─────────────────────────────────────────────────────────
  { name:{en:'Tulsi Mala — 108 Beads for Vishnu Bhaktas',hi:'तुलसी माला — 108 दाने'}, slug:'tulsi-mala-108-vishnu', category:'sacred-mala', description:{en:'Sacred Tulsi mala with 108 genuine tulsi beads in red cotton thread. Purifies aura, removes negativity. For Vishnu and Krishna devotees.',hi:'शुद्ध तुलसी माला 108 दानों के साथ — विष्णु भक्तों के लिए।'}, benefits:['Sacred for Vishnu & Krishna devotees','Purifies aura & removes negativity','Genuine tulsi — certificate included','Best for daily japa & meditation'], price:599, offerPrice:399, images:[img('Tulsi Mala 108')], stock:120, sku:'VA-SM-001', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:3456, rating:4.9, reviewCount:876 },
  { name:{en:'Sphatik Mala — 108 Crystal Beads',hi:'स्फटिक माला — 108 क्रिस्टल दाने'}, slug:'sphatik-mala-108-crystal', category:'sacred-mala', description:{en:'Pure Sphatik (clear quartz crystal) mala with 108+1 beads. Used for japa of all deities, especially recommended for chanting Devi mantras.',hi:'शुद्ध स्फटिक माला 108+1 दानों के साथ — सभी देवी मंत्र जप के लिए।'}, benefits:['Suitable for all deity mantras','Keeps mind cool during japa','Each bead natural, no synthetic','Ideal for Devi & Shiva mantras'], price:1299, offerPrice:899, images:[img('Sphatik Crystal Mala')], stock:78, sku:'VA-SM-002', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:1567, rating:4.8, reviewCount:398 },
  { name:{en:'Chandan (Sandalwood) Mala — 108 Beads',hi:'चंदन माला — 108 दाने'}, slug:'chandan-sandalwood-mala-108', category:'sacred-mala', description:{en:'Fragrant Chandan (white sandalwood) mala with 108+1 handcrafted beads. Natural fragrance enhances focus. For Gayatri Mantra, Ram Naam, Hanuman mantras.',hi:'असली चंदन की खुशबू वाली माला — गायत्री, राम नाम और हनुमान मंत्र के लिए।'}, benefits:['Natural sandalwood fragrance','Enhances focus during japa','Best for Gayatri & Ram mantras','Handcrafted 108+1 beads'], price:899, offerPrice:599, images:[img('Sandalwood Mala 108')], stock:95, sku:'VA-SM-003', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:2234, rating:4.8, reviewCount:567 },
  { name:{en:'Lotus Seed Kamal Gatta Mala — Laxmi Japa',hi:'कमल गट्टा माला — लक्ष्मी जप'}, slug:'lotus-seed-kamal-gatta-mala', category:'sacred-mala', description:{en:"Sacred Kamal Gatta (Lotus seed) mala with 108 beads — the mala of Goddess Lakshmi. Chanting Laxmi mantras brings exceptional wealth and prosperity.",hi:'कमल गट्टा माला — देवी लक्ष्मी की माला। व्यापारियों के लिए सर्वोत्तम।'}, benefits:["Goddess Lakshmi's own mala",'Best for wealth & business mantras','Natural lotus seeds — authentic','Ideal for traders & entrepreneurs'], price:799, offerPrice:499, images:[img('Lotus Seed Mala')], stock:88, sku:'VA-SM-004', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:2876, rating:4.9, reviewCount:712 },
  { name:{en:'Rudraksha Sphatik Combination Mala',hi:'रुद्राक्ष स्फटिक संयोजन माला'}, slug:'rudraksha-sphatik-combination-mala', category:'sacred-mala', description:{en:'Unique combination mala alternating Rudraksha and Sphatik beads — giving the power of both Lord Shiva (protection) and Goddess Shakti (abundance).',hi:'रुद्राक्ष और स्फटिक की संयुक्त माला — शिव और शक्ति की दोहरी ऊर्जा।'}, benefits:['Shiva + Shakti dual power','Protection + Prosperity together','Energised by Dr. PPS IVAF','Perfect balance of 54+54 beads'], price:1599, offerPrice:1099, images:[img('Rudraksha Sphatik Mala')], stock:45, sku:'VA-SM-005', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:765, rating:4.8, reviewCount:198 },

  // ─── MURTHY ───────────────────────────────────────────────────────────────
  { name:{en:'Ganesha Marble Murti — Handcrafted',hi:'गणेश मार्बल मूर्ति — हस्तनिर्मित'}, slug:'ganesha-marble-murti-handcrafted', category:'murthy', description:{en:'Hand-chiselled Ganesha murti in white Makrana marble — same marble as the Taj Mahal. 5 inches. Includes velvet seat and Dr. PPS placement guide.',hi:'मकराना संगमरमर की हस्तनिर्मित गणेश मूर्ति — 5 इंच।'}, benefits:['Removes all obstacles','Makrana marble — premium quality','Velvet seat & placement guide included','Vastu recommended — east facing'], price:2499, offerPrice:1599, images:[img('Ganesha Marble Murti')], stock:28, sku:'VA-MU-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:567, rating:4.9, reviewCount:145 },
  { name:{en:'Lakshmi Brass Murti — 6 Inch Puja Grade',hi:'लक्ष्मी पीतल मूर्ति — 6 इंच पूजा ग्रेड'}, slug:'lakshmi-brass-murti-6inch', category:'murthy', description:{en:'Puja-grade Goddess Lakshmi brass murti — 6 inches tall, approx. 400g. Traditional Dhokra process, gold-antique finish.',hi:'6 इंच लक्ष्मी पीतल मूर्ति — धोकरा प्रक्रिया से निर्मित।'}, benefits:['Puja-grade heavy brass — 400g','Traditional Dhokra casting','Gold antique finish — elegant','North wall placement for wealth'], price:1999, offerPrice:1299, images:[img('Lakshmi Brass Murti')], stock:35, sku:'VA-MU-002', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:789, rating:4.8, reviewCount:201 },
  { name:{en:'Hanuman Panchmukhi Silver-Plated Murti',hi:'पंचमुखी हनुमान सिल्वर प्लेटेड मूर्ति'}, slug:'hanuman-panchmukhi-silver-murti', category:'murthy', description:{en:'Panchmukhi (5-faced) Hanuman for maximum protection and courage. Silver-plated brass, 5 inches. Place in South zone of home or car dashboard.',hi:'5 इंच पंचमुखी हनुमान — सुरक्षा और साहस के लिए।'}, benefits:['Panchmukhi — maximum protection','Silver-plated brass — tarnish-resistant','Car dashboard & home — versatile','South zone Vastu placement'], price:1799, offerPrice:1199, images:[img('Panchmukhi Hanuman Murti')], stock:42, sku:'VA-MU-003', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:623, rating:4.9, reviewCount:167 },
  { name:{en:'Shiva Nataraja Bronze Murti — 4 Inch',hi:'शिव नटराज कांस्य मूर्ति — 4 इंच'}, slug:'shiva-nataraja-bronze-4inch', category:'murthy', description:{en:'Traditional Nataraja (dancing Shiva) murti cast in bronze. Symbolises cosmic dance of creation and destruction. Place in West zone.',hi:'कांस्य शिव नटराज — ब्रह्मांडीय नृत्य का प्रतीक।'}, benefits:['Bronze cast — museum quality','Promotes creativity & art','West zone Vastu placement','Symbol of divine dance & power'], price:2199, offerPrice:1499, images:[img('Nataraja Bronze Murti')], stock:22, sku:'VA-MU-004', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:321, rating:4.7, reviewCount:87 },
  { name:{en:'Kuber Murti — Wealth God Brass Idol',hi:'कुबेर मूर्ति — धन के देव पीतल'}, slug:'kuber-murti-wealth-brass', category:'murthy', description:{en:'Lord Kuber — treasurer of the Gods. Brass murti (5 inches, 300g), Vastu-activated. Place on North wall to attract and retain wealth.',hi:'धन के देव कुबेर पीतल मूर्ति — उत्तर दीवार पर रखें।'}, benefits:['Attracts & retains wealth','North zone Vastu placement','Heavy brass 300g — premium','Activated for wealth magnetism'], price:1599, offerPrice:1099, images:[img('Kuber Brass Murti')], stock:31, sku:'VA-MU-005', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:456, rating:4.8, reviewCount:119 },

  // ─── SHOP BY RASHI ────────────────────────────────────────────────────────
  { name:{en:'Mesh Rashi (Aries) Crystal Kit',hi:'मेष राशि क्रिस्टल किट'}, slug:'mesh-rashi-aries-crystal-kit', category:'rashi', description:{en:'Curated crystal kit for Mesh Rashi (Aries, Mar 21 – Apr 19). Includes Bloodstone, Red Jasper, and Clear Quartz. Personalised Rashi card & placement guide included.',hi:'मेष राशि के लिए क्रिस्टल किट — ब्लडस्टोन, रेड जैस्पर, क्लियर क्वार्ट्ज।'}, benefits:['3 curated crystals for Mesh Rashi','Personalised Rashi card included','Dr. PPS usage guide','Activates Mars energy (ruler of Aries)'], price:1499, offerPrice:999, images:[img('Mesh Rashi Crystal Kit')], stock:40, sku:'VA-RS-001', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:456, rating:4.7, reviewCount:118 },
  { name:{en:'Vrishabha Rashi (Taurus) Healing Kit',hi:'वृषभ राशि हीलिंग किट'}, slug:'vrishabha-rashi-taurus-healing-kit', category:'rashi', description:{en:'Vrishabha Rashi crystal healing kit for Taurus (Apr 20 – May 20). Includes Rose Quartz, Green Aventurine, and Malachite. Venus-energy crystals.',hi:'वृषभ राशि के लिए क्रिस्टल किट।'}, benefits:['3 Venus-energy crystals','Boosts love & financial growth','Personalised Rashi guidance','Ideal for stable sign individuals'], price:1499, offerPrice:999, images:[img('Taurus Rashi Crystal Kit')], stock:35, sku:'VA-RS-002', isFeatured:false, isNewLaunch:true, isActive:true, totalSold:312, rating:4.8, reviewCount:89 },
  { name:{en:'Mithun Rashi (Gemini) Mercury Kit',hi:'मिथुन राशि मर्करी किट'}, slug:'mithun-rashi-gemini-mercury-kit', category:'rashi', description:{en:'Mithun Rashi kit for Gemini (May 21 – Jun 20). Includes Agate, Blue Lace Agate, and Citrine. Mercury-activated crystals for quick-minded Gemini.',hi:'मिथुन राशि के लिए मर्करी क्रिस्टल किट।'}, benefits:['Mercury-activated crystals','Enhances communication skills','Boosts mental agility','Best for writers, speakers & traders'], price:1499, offerPrice:999, images:[img('Gemini Rashi Crystal Kit')], stock:38, sku:'VA-RS-003', isFeatured:false, isNewLaunch:false, isActive:true, totalSold:278, rating:4.7, reviewCount:74 },
  { name:{en:'Karka Rashi (Cancer) Moon Energy Kit',hi:'कर्क राशि मून एनर्जी किट'}, slug:'karka-rashi-cancer-moon-kit', category:'rashi', description:{en:'Karka Rashi Moon Energy Kit for Cancer (Jun 21 – Jul 22). Includes Moonstone, Pearl, and Selenite. Moon-activated, perfect for emotionally sensitive Cancer natives.',hi:'कर्क राशि मून किट — मूनस्टोन, पर्ल, सेलेनाइट।'}, benefits:['Moon-activated crystals','Soothes emotional sensitivity','Enhances intuition & empathy','Moonstone + Pearl combo — rare'], price:1799, offerPrice:1199, images:[img('Cancer Moon Crystal Kit')], stock:29, sku:'VA-RS-004', isFeatured:true, isNewLaunch:false, isActive:true, totalSold:345, rating:4.9, reviewCount:92 },
  { name:{en:'Simha Rashi (Leo) Sun Power Kit',hi:'सिंह राशि सन पावर किट'}, slug:'simha-rashi-leo-sun-power-kit', category:'rashi', description:{en:'Simha Rashi Sun Power Kit for Leo (Jul 23 – Aug 22). Includes Pyrite, Sunstone, and Tiger Eye. Sun-activated kit for the natural-born leader.',hi:'सिंह राशि के लिए सन पावर किट।'}, benefits:['Sun-activated power crystals','Boosts leadership & recognition','Strengthens self-expression','Pyrite + Tiger Eye — career combo'], price:1699, offerPrice:1099, images:[img('Leo Sun Power Crystal Kit')], stock:33, sku:'VA-RS-005', isFeatured:true, isNewLaunch:true, isActive:true, totalSold:421, rating:4.8, reviewCount:108 },
];

export async function seedProducts(): Promise<{ inserted: number; skipped: number }> {
  let inserted = 0;
  let skipped = 0;
  for (const product of SAMPLE_PRODUCTS) {
    const exists = await Product.findOne({ slug: product.slug });
    if (exists) { skipped++; } else { await Product.create(product); inserted++; }
  }
  (console as any).log(`[Seed] Products: ${inserted} inserted, ${skipped} already existed.`);
  return { inserted, skipped };
}
